### ISSUE TITLE
Graph of time in heart rate zones

### ISSUE THREAD

**Issue by smatthie** [tcgoetz/GarminDB#107]
**Is your feature request related to a problem? Please describe.**
Not a problem, but for general health and activity monitoring it's useful to know how much time one spends in the different heart rate zone, not just the resting rate and the maximum. 

**Describe the solution you'd like**
A graph that shows how much time one has spent in the different heart rate zones (1 to 5) every day. I wear the watch all the time (except for charging).

This could be a stacked bar chart where days are along the bottom axis, with each days having stacked bars in different colours for the time in heart rate zones. 

**Describe alternatives you've considered**
The database has a table with the heart rate every minute (at least it has for my device, I don't know if this is so for all devices), so it should be straightforward to count how many minutes fall into each heart rate zone every day and create a stacked bar chart from that.

It should probably exclude times in the resting heart rate or below some other good threshold, otherwise the lowest bar will dominate the graph too much, given that one spends only a few minutes out of 24 hours in the highest HR zone.

**Also...:**
Also, thank you very much for creating this. It is very useful and I've looked for a long time for a way to export the Garmin data to my own computer.

**Comment by tcgoetz** [comment]
Jupyter notebook now has a table not a graph of heart rate time in zones. Not planning a graph atm.
