### ISSUE TITLE
Download: 402 Client Error

### ISSUE THREAD

**Issue by ChronicAdrift** [tcgoetz/GarminDB#109]
**Describe the bug**
`make create_dbs` produces a 402 Client Error. Download errors.
The console prints:
```
/usr/bin/time /usr/bin/python3.7 garmin.py --all --download --import --analyze
___Downloading All Data___
Geting activities: '/HealthData/FitFiles/Activities' (1000) temp /tmp/tmpzso51vj4
0activities [00:00, ?activities/s]
Traceback (most recent call last):
  File "garmin.py", line 341, in <module>
    main(sys.argv[1:])
  File "garmin.py", line 322, in main
    download_data(args.overwrite, args.latest, args.stats)
  File "garmin.py", line 127, in download_data
    download.get_activities(activities_dir, activity_count, overwite)
  File "/GarminDB/download_garmin.py", line 283, in get_activities
    for activity in tqdm(activities, unit='activities'):
  File "/.local/lib/python3.7/site-packages/tqdm/std.py", line 1170, in __iter__
    for obj in iterable:
TypeError: 'NoneType' object is not iterable
Command exited with non-zero status 1
```

**To Reproduce**
I just installed from source on Linux (`5.4.0-65-generic #73~18.04.1-Ubuntu SMP Tue Jan 19 09:02:24 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`). But with `git clone --recursive https://github.com/tcgoetz/GarminDB.git` instead of SSH and ran `make setup` (without `update`), then `make create_dbs`.

**Expected behavior**
I was expecting a full download and not an erroring response.

**Logs**
The log clearly shows the <Response [402]>.
[garmin.log](https://github.com/tcgoetz/GarminDB/files/6032753/garmin.log)
Python 3.6.9, GarminDB version garmin.py 2.0.1

**Additional context**
The error code might sign the response is too large, but I'm unsure about that. Even with 100 and 10 as limit the same error occurs.

**Comment by matthiaswh** [comment]
I started seeing this yesterday as well.

Tracking down that request in connect.garmin.com, it looks like there is a header `nk: NT` being sent with the request. No idea what that indicates, but when I remove that from it I start seeing a 402 response.

**Comment by telemaxx** [comment]
ü

**Comment by skrasnow** [comment]
Very similar issue.  Trying to update the Garmin database using version 1.8.1 from binaries.  Terminal output is:
_DB_1.8.1/GarminDb_Darwin_1.8.1/download_update_dbs.sh 
Updating existing DBs by downloading from Garmin Connect
___Downloading Latest Data___
Geting activities: '/Users/stanleykrasnow/HealthData/FitFiles/Activities' (10) temp /var/folders/52/658fj6dn45z3pd_djghmxw6r0000gn/T/tmpjgbxnlwh
0activities [00:00, ?activities/s]
Traceback (most recent call last):
  File "garmin.py", line 340, in <module>
  File "garmin.py", line 321, in main
  File "garmin.py", line 122, in download_data
  File "download_garmin.py", line 283, in get_activities
  File "tqdm/std.py", line 1171, in __iter__
TypeError: 'NoneType' object is not iterable
[64680] Failed to execute script garmin

**Comment by smatthie** [comment]
Same issue here, and I can confirm that it works again for me when I add the header "nk: NT" in rest_client.py as described in the fix above.

**Comment by tcgoetz** [comment]
I implemented it differently here 62d9a50. Utilities is generic code and shouldn't have anything Garmin specific in it.

**Comment by tcgoetz** [comment]
Let me know if the fix works for you and I will merge it to master and make a release after I get some positive feedback.

**Comment by smatthie** [comment]
@tcgoetz Yes, that works for me.
