### ISSUE TITLE
garmin-connect-export submodule not pushed to github

### ISSUE THREAD

**Issue by earlyday** [tcgoetz/GarminDB#11]
I guess the submodule was not pushed to github on the latest commit.

**Comment by tcgoetz** [comment]
Which one? Whats the error?

**Comment by earlyday** [comment]
The last commit two days ago on GarminDB depends on a non existing sha in
garmin-connect-export.

mån 23 apr. 2018 kl. 22:57 skrev Tom Goetz <notifications@github.com>:

**Comment by tcgoetz** [comment]
Submodules are a PITA. Everything looks right from my side:

```
orion-wl:garmin-connect-export tgoetz$ git log
commit 85da1a10296e94d38d785e9f756d3cb10dc3407e (HEAD -> pull_req_42)
Author: Tom Goetz <tom.goetz@virtualcomputer.com>
Date:   Sat Apr 21 19:26:03 2018 -0400

    port orig repo pull req 42 to add support for new API

commit ab949368b065aa05530566ffa255290e01b0605f (origin/pr/4)
Author: Kyle Krafka <kyle.krafka@gmail.com>
Date:   Tue Dec 22 22:26:24 2015 -0500

    A few fixes after testing a complete export
...
```

and 

```
orion-wl:garmin-connect-export tgoetz$ git push
Everything up-to-date
orion-wl:garmin-connect-export tgoetz$ git status
On branch pull_req_42
```

I'll look at it some more.

**Comment by earlyday** [comment]
This is very strange to me.

I don't understand this. I cloned again and now I get the right stuff.

My first attempt resulted in this history, which is different from what I
see after a new clone.

I will carry on with make setup but get compiler errors.

commit 93b24c29bac316fe2b8e5888f4d8f81a2769e8a9
Author: Tom Goetz <tom.goetz@virtualcomputer.com>
Date:   Tue Mar 27 09:04:24 2018 -0400

    handle json data with no summary

 gcexport.py | 8 +++++---
 1 file changed, 5 insertions(+), 3 deletions(-)

commit df66b0b8eb2ea7e6a542582e9e82f012c543378c
Author: Tom Goetz <tom.goetz@virtualcomputer.com>
Date:   Sun Mar 4 14:31:07 2018 -0500

    log saving json data

 gcexport.py | 1 +
 1 file changed, 1 insertion(+)

commit 87f0d101000e90ad590ddb526544138f704833b9
Author: Tom Goetz <tom.goetz@virtualcomputer.com>
Date:   Sat Feb 24 09:09:32 2018 -0500

    remove debugging exit

 gcexport.py                   |   1 -
 old/garmin-connect-export.php | 245
----------------------------------------------------------------------------------------------------------------------------------
 2 files changed, 246 deletions(-)


2018-04-24 2:50 GMT+02:00 Tom Goetz <notifications@github.com>:

**Comment by tcgoetz** [comment]
> I will carry on with make setup but get compiler errors.

What compiler errors? Not sure what should be compiling. Think it's all Python.

**Comment by earlyday** [comment]
I very much appreciate the effort you do.

I have tried in various ways and the compilation happens in tcxparser.
I managed to go around this and can now run gcexport.py but the
scrape_garmin.py requires a working firefoxdriver and selenium.
Apparently, my install don't have the webdriver.xpi and after fixing it I
end up in more errors about missing x_ignore_nofocus.so.

I guess this require some effort to make it work on debian stretch.

What os are you running?

/Erland

2018-04-24 13:42 GMT+02:00 Tom Goetz <notifications@github.com>:

**Comment by tcgoetz** [comment]
I'm on OSX.

There is code in the "make deps" to install the Firefox driver for Linux, but it hasn't been tested. If you can get it working, please submit a patch.

**Comment by earlyday** [comment]
Hi, I solved some by installing selenium using pip, instead of apt-get. Later I was required to add headless option as firefox option. I could not push to you repo so pick up the patch here:
[https://github.com/earlyday/sandbox/blob/master/headless.patch](url)

**Comment by tcgoetz** [comment]
I've updated the code to download weight and monitoring files via the GC API. No more scraping. No more Firefox needed.

**Comment by earlyday** [comment]
Testing, but missing commit 0c0b0a57ee6b084b2a03c448add8b01382eaca15 in Fit.

2018-04-30 3:36 GMT+02:00 Tom Goetz <notifications@github.com>:

**Comment by tcgoetz** [comment]
Try it again.

**Comment by earlyday** [comment]
Perfect.

tis 1 maj 2018 kl. 13:53 skrev Tom Goetz <notifications@github.com>:

**Comment by tcgoetz** [comment]
Is everything working for you now? Can we close this bug?

**Comment by earlyday** [comment]
Yes consider it solved.  Thank you.

tors 3 maj 2018 kl. 16:36 skrev Tom Goetz <notifications@github.com>:
