### ISSUE TITLE
No aditional_headers attribute in RestClient

### ISSUE THREAD

**Issue by lpierron** [tcgoetz/GarminDB#117]
There is no `aditional_headers` attribute in `RestClient` 

https://github.com/tcgoetz/GarminDB/blob/dd9cc54a106b0a613516afbbfa0532adc9047bf1/download_garmin.py#L64

**Comment by tcgoetz** [comment]
There is is the current version: https://github.com/tcgoetz/utilities/blob/672fb386161fc9cce1545ea89bc61248a3c95fa0/rest_client.py#L75

Your utilities submodule is out of date. You need to update the submodules when you update the main repo: `make update`
