### ISSUE TITLE
Updating data is reparsing every fit file every time after migration

### ISSUE THREAD

**Issue by awaisas** [tcgoetz/GarminDB#118]
After setting up a new GarminDB on my Linux box, I copied over my HealthData folder from my Mac. I have used rebuild_dbs and all the data seems to be in the DBs and updating using make works fine. However, every time I update the script is reparsing all the fit files which takes some time. Is there some way to fix this?

**Comment by tcgoetz** [comment]
It will stop re-parsing them in a day or so. Since you copied them all the dates are all new.
