### ISSUE TITLE
"make" always *analyzes* also old data

### ISSUE THREAD

**Issue by giterest** [tcgoetz/GarminDB#121]
**Describe the bug**
I initally retrieved all data from my Garmin account (make create_dbs). Now, I wanted to only download/analyze latest data via make. "Downloading" works, "Importing" works, but when it comes to "Analyzing", it will always start /w "Generating table entries for 2016" - and looping through all the years until 2021 takes a couple of hours.

**To Reproduce**
1. run "make"
2. wait for "___Analyzing Data___"
3. it will parse *all* data, not only *recent additions*

**Expected behavior**
Only analyze recent/new data.

**Logs**
```
INFO:/usr/local/garmindb/GarminDB/analyze_garmin.py:Summary Tables Generation:
INFO:/usr/local/garmindb/GarminDB/analyze_garmin.py:Generating table entries for 2016
```

**Please run bugreport.sh and attach bugreport.zip.**

**Additional context**

**Comment by tcgoetz** [comment]
How long has it been since you downloaded all the data? Import, imports all files with dates no more than 24 hours old.

**Comment by giterest** [comment]
hi there, e.g. the oldest files at /HealthData/FitFiles/Monitoring/2016 have a last change timestamp of 23rd may 2021, 11:43 (CEST).
the last time i ran make was today around 07:00 (CEST) - so there were ~43h in between.

from my perspective, downloading and importing works fine - but at the analyze step, it will always analyze also files from 2016, 2017, ... and so on.

thanks for coming back, much appreciated!

**Comment by giterest** [comment]
hi. started another try (first one since my last post, so more than 2 days). as soon as [make] hits "___Analyzing Data___" it starts from the very beginning (2016...) and finishing to 2021 takes approx. 10-12h.

**Comment by lpierron** [comment]
I have the same issue, but it's not a problem for me, analyzing a year takes about 30 seconds not 10 hours.
```
make
...
___Analyzing Data___
Summary Tables Generation:
...
Generating table entries for 2019
100%|█████████████████████| 365/365 [00:24<00:00, 14.96days/s]
100%|█████████████████████| 52/52 [00:04<00:00, 10.71weeks/s]
100%|█████████████████████| 12/12 [00:02<00:00,  5.14months/s]
...
```

**Comment by giterest** [comment]
weird.. i run garmindb on a debian buster VM with 4 cpus and 8gig of ram. i use that VM solely for testing, so there's nothing else running on it.

**Comment by lpierron** [comment]
I think it's a problem with your installation of `sqlite3`, could you reinstall it on your VM and make some tests.

If you don't use the DB, I think you can just download the latest datas:
```
garmin.py --all --download --import  --latest
```

**Comment by j-paulus** [comment]
It seems that the call to `Analyze.summary()` defined in `analyze_garmin.py` loops over all years in the DB and creates the summary tables even if the data weren't changed. 
I too have been wondering this behaviour, but since the it runs relatively quickly, never thought it as a significant problem.

**Comment by giterest** [comment]
thanks for the tip, reinstalled sqlite3 package on test-VM and also installed GarminDB on my PROD machine - same behaviour. i also checked sysload during the analysis, there's no significant change in utilization, so the root cause (in my case) is not based on system resources.

**Comment by giterest** [comment]
profiling runs.. will come back asap as i have some results to share.

**Comment by tcgoetz** [comment]
I misunderstood your issue when I said it only does the latest. Download and import take a --latest option, but analyze always analyzes all of the DB data. I've never seen a need to optimize it since it is fast for me. Analyze reads and writes the database a lot. I would guess that your database access is slow. The database itself is a file, so I would guess either your VM doesn't have enough RAM to cache the DB file or your VMs IO is slow.

**Comment by giterest** [comment]
hi all, so it seems that on TEST the sqlite-DB got somehow corrupted, causing garmindb to have that immense I/O times.
anyhow, on PROD it runs fine (~12-15mins), after copying PROD-db to TEST, it also takes 12-15mins there per "make".

only thing "left" would be to discuss if ALL db data has to be analyzed always(?)

thanks for your kind support and time!
