### ISSUE TITLE
Login to Garmin Connect is Broken again

### ISSUE THREAD

**Issue by tcgoetz** [tcgoetz/GarminDB#123]
Other projects like https://github.com/cyberjunky/python-garminconnect don't have a solution yet. If you know of a tool that is currently successfully logging in to Garmin Connect please post it to this bug.

**Comment by tcgoetz** [comment]
https://github.com/cyberjunky/python-garminconnect/issues/52

**Comment by EmptySoft** [comment]
Maybe I misunderstand the question, for me your program GarminDB works with the change from lpierron

https://github.com/tcgoetz/GarminDB/issues/120#issuecomment-843942390

But I sync only 1 time a day, if I sync every hour I get locked every few days and have to change the password on the website

**Comment by tcgoetz** [comment]
I didn't mean that it is totally broken. I meant that you couldn't run if often or you would get locked out and have to relogin to the website.

**Comment by lpierron** [comment]
I have the same problem, sometimes the connection works well like this morning. Sometimes I have to run again 3 or 4 times before the connection is accepted. I have no idea about the problem.

**Comment by giterest** [comment]
same here... i run make every third day via cron, but from time to time the login seem to fail (even with https://github.com/tcgoetz/GarminDB/issues/120#issuecomment-843942390).

**Comment by Dave-DigiMim** [comment]
I use garpy and they had teh same issue . I just did a loop up to ten times to recall login and it worked fine.. Not elegant but it works.
