### ISSUE TITLE
Custom output directory

### ISSUE THREAD

**Issue by ghzgod** [tcgoetz/GarminDB#126]
Hello tcgoetz, great tool been using it for about 2 years now.  Is there a way to specify the output directory etc?  When I run the tool it wants my config to exist at /root/.GarminDb/ and HealthData, .config, and .cache also get created in my /root/ directory.  This happens even if I run the tool in a different directory.  Is this normal behavior or can we change the working directory?

**Comment by tcgoetz** [comment]
The directories for config and data are defined in https://github.com/tcgoetz/GarminDB/blob/master/garmindb/config.py
