### ISSUE TITLE
AttributeError: 'sessionmaker' object has no attribute 'begin'

### ISSUE THREAD

**Issue by cmartin** [tcgoetz/GarminDB#127]
When running 

`garmindb_cli.py --all --download --import --analyze`

from a pip3 install (v3.0.2), I get the following error message after the downloads completes : 

`AttributeError: 'sessionmaker' object has no attribute 'begin'`

I'm running on MacOS and data comes from an old forerunner and a new vivosmart 4 if it is of any help.

**Comment by tcgoetz** [comment]
This is a dupe of Issue #124 . Your SQLAlchemy is out of date. See #124 for details. Future versions of GarminDb will have the requirement for a newer SQLAlchemy built into the package.

**Comment by cmartin** [comment]
Ah, yeah, that worked. Sorry about missing that other ticket.
