### ISSUE TITLE
Changing credential in config file does still download data from former credentials

### ISSUE THREAD

**Issue by Minimic-beep** [tcgoetz/GarminDB#135]
**Describe the bug**
Changing credentials in GarminConnectConfig.json file appears that it somehow caches the token / credentials elsewhere, ignores the change in config file, and keeps downloading data from the original user that was first used to download the data.

**To Reproduce**
1. set credentials of user A in config file
2. run garmindb_cli.py to fetch data
3. change username and password for another garmin user in config file
4. run the script again to download data from a new user
5. the script downloads the very same data as before therefore from the former user, instead of the new user

**Expected behavior**
When I change user account in conf file the scripts should download data from that user and not some cached credentials/tokens

**Comment by tcgoetz** [comment]
Are you on MacOS? Do you have the secure password setting? Is it reading the password from the keychain?

**Comment by tcgoetz** [comment]
Closing as old. Reopen if it reproduces with current builds.
