### ISSUE TITLE
Allow custom location for HealthData in configuration

### ISSUE THREAD

**Issue by raphaelfournier** [tcgoetz/GarminDB#136]
This issue is clearly linked to #126. The need is to allow the user to change the location of the HealthData folder.

The provided answer in #126 works in the "build from source" method, with which one may alter the file `config.py`. In the "install with pip" method, one has to rely on the `.GarminDb/GarminConnectConfig.json` file, which currently does not enable to change such a location.

**Comment by tcgoetz** [comment]
With dd71124fb21d9f911869925a4aeae2d9444c1e8e this is now possible in the regular config file.
