### ISSUE TITLE
Precess terminates when building summary files for 2021

### ISSUE THREAD

**Issue by skrasnow** [tcgoetz/GarminDB#137]
Per the attached PDF when doing my daily db update, the process terminates when building the 2021 summary file with the message "database disk image is malformed".  To recover believe that I have to run a make command ro rebuild from data previously downloaded.  But, I can't figure out how to do so.  I am running from a software stack installed on OSX with pip3.  Thank you.
[garmin_db screen shots.pdf](https://github.com/tcgoetz/GarminDB/files/7643680/garmin_db.screen.shots.pdf)
u.

**Comment by tcgoetz** [comment]
To rebuild your database, delete the DB files in HealthData/DBs/*.db then run ```garmindb_cli.py --all --import --analyze```

**Comment by skrasnow** [comment]
Thank you, Tom!
