### ISSUE TITLE
Body battery information

### ISSUE THREAD

**Issue by laurapoggio-sptools** [tcgoetz/GarminDB#138]
Are the body battery data already downloaded?
Would be possible to add them?

Thanks

**Comment by tcgoetz** [comment]
My summary files in HealthData/FitFiles/Monitoring/*/daily_summary_*.json have the following fields:

> 
>     "bodyBatteryChargedValue": 45,
>     "bodyBatteryDrainedValue": 2,
>     "bodyBatteryHighestValue": 89,
>     "bodyBatteryLowestValue": 46,
>     "bodyBatteryMostRecentValue": 89,
>     "bodyBatteryVersion": 2.0,
> 

I assume your's do to. So it's already downloaded, just not in the database. Adding it to the database would not be hard, but would require a schema change. All databases would need to be deleted and rebuilt after the new version was downloaded.

I'll look at when it could be added.

**Comment by tcgoetz** [comment]
Which fields are you interested in?

**Comment by laurapoggio-sptools** [comment]
Thanks a lot for looking into this. For me the most interesting fields would be `"bodyBatteryHighestValue"` and `"bodyBatteryLowestValue"`.

**Comment by tcgoetz** [comment]
I have added support on the develop branch. If you are able to work from source please try it out and give feedback. Otherwise I will merge to master and release sometime soon.

**Comment by laurapoggio-sptools** [comment]
I am fine with working from source. I started the process. As I did not have the DBs anymore due to a laptop problem, it is downloading everything again and it may take a while. For the moment it is working. I will report back once the DBs have been build. Thanks a lot!

**Comment by laurapoggio-sptools** [comment]
I am getting the error below, even if I delete the DBs before starting with `make setup`:
```
Processing [<FileType.activity: 4>] FIT data from /home/poggi002/HealthData/FitFiles/Activities
___Analyzing Data___
Traceback (most recent call last):
  File "/home/user/.local/bin/garmindb_cli.py", line 355, in <module>
    main(sys.argv[1:])
  File "/home/user/.local/bin/garmindb_cli.py", line 342, in main
    analyze_data(args.trace)
  File "/home/user/.local/bin/garmindb_cli.py", line 231, in analyze_data
    analyze = Analyze(db_params_dict, debug - 1)
  File "/home/user/.local/lib/python3.9/site-packages/garmindb/analyze.py", line 37, in __init__
    self.garmin_sum_db = GarminSummaryDb(db_params, debug)
  File "/home/user/.local/lib/python3.9/site-packages/idbutils/db.py", line 66, in __init__
    self.init_table(table)
  File "/home/user/.local/lib/python3.9/site-packages/idbutils/db.py", line 77, in init_table
    self.attributes.table_version_check(self, table)
  File "/home/user/.local/lib/python3.9/site-packages/idbutils/db_attributes.py", line 34, in table_version_check
    raise RuntimeError("DB: %s table %s version mismatch. The DB schema has been updated. Please rebuild the %s DB. (%s vs %s)" %
RuntimeError: DB: garmin_summary table years_summary version mismatch. The DB schema has been updated. Please rebuild the garmin_summary DB. (4 vs 5)
make: *** [Makefile:192: update_garmin] Error 1
```

**Comment by tcgoetz** [comment]
How did you delete the DB files? By hand on the command line or with the --delete_db or --rebuild_db? If the later, try deleting the files by hand. Maybe there is a bug in --delete_db or --rebuild_db.

**Comment by laurapoggio-sptools** [comment]
I did it manually. I am trying again.

**Comment by lpierron** [comment]
It sounds that the new database creation is very slow, processing monitoring (19342 files) took more than 11 hours:
```
% make create_dbs
garmindb_cli.py --all --download --import --analyze
___Downloading All Data___
Geting activities: '/Users/pierron/HealthData/FitFiles/Activities' (3000) temp /var/folders/rc/g12p3yvx1n72fpjhnlgxt1tm0000gr/T/tmpi4vo0pdk
....
Processing daily summary data
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1436/1436 [01:56<00:00, 12.38files/s]
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1436/1436 [02:12<00:00, 10.86files/s]
Processing [<FileType.monitoring_b: 32>] FIT data from /Users/pierron/HealthData/FitFiles/Monitoring
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████| 19342/19342 [11:26:50<00:00,  2.13s/files]
Processing sleep data
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1436/1436 [03:19<00:00,  7.20files/s]
Processing rhr data
....
```

Until now creating databases it's not finished, and I see an error in processing Activities FIT Data:
```
Processing [<FileType.activity: 4>] FIT data from /Users/pierron/HealthData/FitFiles/Activities
 12%|█████████████                                                                                                    | 143/1243 [14:27<1:07:28,  3.68s/files]Failed to write message <MessageType.session: 18> type DataMessage(<MessageType.session: 18>: [timestamp(datetime.datetime(2020, 11, 7, 20, 5, 17, tzinfo=datetime.timezone.utc) (973713917)), start_time(datetime.datetime(2020, 11, 7, 19, 49, 25, tzinfo=datetime.timezone.utc) (973712965)), start_position_lat([invalid] (Latitude(invalid))), start_position_long([invalid] (Longitude(invalid))), total_elapsed_time(datetime.time(0, 15, 38) (938000)), total_timer_time(datetime.time(0, 15, 38) (938000)), total_distance([invalid] (Distance(invalid))), total_cycles([invalid] cycles (4294967295)), nec_lat([invalid] (Latitude(invalid))), nec_long([invalid] (Longitude(invalid))), swc_lat([invalid] (Latitude(invalid))), swc_long([invalid] (Longitude(invalid))), end_position_lat([invalid] (Latitude(invalid))), end_position_long([invalid] (Longitude(invalid))), avg_stroke_count([invalid] (4294967295)), total_work([invalid] J (4294967295)), total_swim_time([invalid] (4294967295)), sport_name('Ex. respiration' ([69, 120, 46, 32, 114, 101, 115, 112, 105, 114, 97, 116, 105, 111, 110, 0])), avg_speed([invalid] (Speed(invalid))), max_speed([invalid] (Speed(invalid))), unknown_152(0.0), message_index({'selected': False, 'value': 0} (0)), total_calories(0.0 kcal), avg_power([invalid] watts (65535)), max_power([invalid] watts (65535)), total_ascent([invalid] (Distance(invalid))), total_descent([invalid] (Distance(invalid))), first_lap_index(0), num_laps(253), length_count([invalid] (65535)), normalized_power([invalid] watts (65535)), training_stress_score([invalid] (65535)), intensity_factor([invalid] (65535)), left_right_balance([invalid] (65535)), avg_stroke_distance([invalid] (Distance(invalid))), pool_length([invalid] (Distance(invalid))), threshold_power([invalid] watts (65535)), num_active_lengths([invalid] (65535)), average_stroke([invalid] (65535)), swolf([invalid] (65535)), avg_stance_time_percent([invalid] % (65535)), avg_stance_time([invalid] (65535)), unknown_151(0.0), unknown_157([invalid] (65535)), unknown_158([invalid] (65535)), avg_respiration_rate(4.41 brpm (441)), max_respiration_rate(5.47 brpm (547)), unknown_177([invalid] (65535)), fluid_consumed(93.0), unknown_179([invalid] (65535)), min_respiration_rate(3.63 brpm (363)), unknown_189(1600.0), unknown_190(9100.0), event(<UnknownEnumValue.UnknownEnumValue_1: 1>), sport(<Sport.training: 10> <bound method SportField.units of <class 'fitfile.activity_fields.SportField'>> (10)), sub_sport(<UnknownEnumValue.UnknownEnumValue_62: 62>), avg_heart_rate(80.0 bpm), max_heart_rate(101.0 bpm), avg_cadence([invalid] rpm (255)), max_cadence([invalid] rpm (255)), total_training_effect([invalid] (255)), event_group([invalid] (255)), session_trigger(<SessionTrigger.activity_end: 0> (0)), swim_stroke([invalid] (255)), pool_length_unit([invalid] (255)), avg_temperature([invalid] (Temperature(invalid))), max_temperature([invalid] (Temperature(invalid))), unknown_81(0.0), avg_fractional_cadence([invalid] rpm (255)), max_fractional_cadence([invalid] rpm (255)), total_fractional_cycles([invalid] cycles (255)), unknown_109([invalid] (255)), sport_index([invalid] (255)), unknown_147([invalid] (255)), unknown_148([invalid] (255)), unknown_149([invalid] (255)), min_temperature([invalid] (Temperature(invalid))), unknown_184(0.0), unknown_194([invalid] (255)), unknown_195(50.0)]): 'UnknownEnumValue' object has no attribute 'preferred'
```

The commit I'm using:
`commit 093f4201e11e189f6d24f14a73af1c962950923c (HEAD -> develop, origin/develop)`

**Comment by lpierron** [comment]
```
> I am getting the error below, even if I delete the DBs before starting with `make setup`:
> 
> ```
> Processing [<FileType.activity: 4>] FIT data from /home/poggi002/HealthData/FitFiles/Activities
> ___Analyzing Data___
> Traceback (most recent call last):
>   File "/home/user/.local/bin/garmindb_cli.py", line 355, in <module>
>     main(sys.argv[1:])
>   File "/home/user/.local/bin/garmindb_cli.py", line 342, in main
>     analyze_data(args.trace)
>   File "/home/user/.local/bin/garmindb_cli.py", line 231, in analyze_data
>     analyze = Analyze(db_params_dict, debug - 1)
>   File "/home/user/.local/lib/python3.9/site-packages/garmindb/analyze.py", line 37, in __init__
>     self.garmin_sum_db = GarminSummaryDb(db_params, debug)
>   File "/home/user/.local/lib/python3.9/site-packages/idbutils/db.py", line 66, in __init__
>     self.init_table(table)
>   File "/home/user/.local/lib/python3.9/site-packages/idbutils/db.py", line 77, in init_table
>     self.attributes.table_version_check(self, table)
>   File "/home/user/.local/lib/python3.9/site-packages/idbutils/db_attributes.py", line 34, in table_version_check
>     raise RuntimeError("DB: %s table %s version mismatch. The DB schema has been updated. Please rebuild the %s DB. (%s vs %s)" %
> RuntimeError: DB: garmin_summary table years_summary version mismatch. The DB schema has been updated. Please rebuild the garmin_summary DB. (4 vs 5)
> make: *** [Makefile:192: update_garmin] Error 1
> 
```

Same problem, after more than half a day of downloading. GRRRR !

So I'd manually removed dbs and restarting `make create_dbs` after installing Python3.9.9.

**Comment by tcgoetz** [comment]
> ```
> 
> ```
> 
> 
>     
>   
> 
> Until now creating databases it's not finished, and I see an error in processing Activities FIT Data:
> 
> ```
> Processing [<FileType.activity: 4>] FIT data from /Users/pierron/HealthData/FitFiles/Activities
>  12%|█████████████                                                                                                    | 143/1243 [14:27<1:07:28,  3.68s/files]Failed to write message <MessageType.session: 18> type DataMessage(<MessageType.session: 18>: [timestamp(datetime.datetime(2020, 11, 7, 20, 5, 17, tzinfo=datetime.timezone.utc) (973713917)), start_time(datetime.datetime(2020, 11, 7, 19, 49, 25, tzinfo=datetime.timezone.utc) (973712965)), start_position_lat([invalid] (Latitude(invalid))), start_position_long([invalid] (Longitude(invalid))), total_elapsed_time(datetime.time(0, 15, 38) (938000)), total_timer_time(datetime.time(0, 15, 38) (938000)), total_distance([invalid] (Distance(invalid))), total_cycles([invalid] cycles (4294967295)), nec_lat([invalid] (Latitude(invalid))), nec_long([invalid] (Longitude(invalid))), swc_lat([invalid] (Latitude(invalid))), swc_long([invalid] (Longitude(invalid))), end_position_lat([invalid] (Latitude(invalid))), end_position_long([invalid] (Longitude(invalid))), avg_stroke_count([invalid] (4294967295)), total_work([invalid] J (4294967295)), total_swim_time([invalid] (4294967295)), sport_name('Ex. respiration' ([69, 120, 46, 32, 114, 101, 115, 112, 105, 114, 97, 116, 105, 111, 110, 0])), avg_speed([invalid] (Speed(invalid))), max_speed([invalid] (Speed(invalid))), unknown_152(0.0), message_index({'selected': False, 'value': 0} (0)), total_calories(0.0 kcal), avg_power([invalid] watts (65535)), max_power([invalid] watts (65535)), total_ascent([invalid] (Distance(invalid))), total_descent([invalid] (Distance(invalid))), first_lap_index(0), num_laps(253), length_count([invalid] (65535)), normalized_power([invalid] watts (65535)), training_stress_score([invalid] (65535)), intensity_factor([invalid] (65535)), left_right_balance([invalid] (65535)), avg_stroke_distance([invalid] (Distance(invalid))), pool_length([invalid] (Distance(invalid))), threshold_power([invalid] watts (65535)), num_active_lengths([invalid] (65535)), average_stroke([invalid] (65535)), swolf([invalid] (65535)), avg_stance_time_percent([invalid] % (65535)), avg_stance_time([invalid] (65535)), unknown_151(0.0), unknown_157([invalid] (65535)), unknown_158([invalid] (65535)), avg_respiration_rate(4.41 brpm (441)), max_respiration_rate(5.47 brpm (547)), unknown_177([invalid] (65535)), fluid_consumed(93.0), unknown_179([invalid] (65535)), min_respiration_rate(3.63 brpm (363)), unknown_189(1600.0), unknown_190(9100.0), event(<UnknownEnumValue.UnknownEnumValue_1: 1>), sport(<Sport.training: 10> <bound method SportField.units of <class 'fitfile.activity_fields.SportField'>> (10)), sub_sport(<UnknownEnumValue.UnknownEnumValue_62: 62>), avg_heart_rate(80.0 bpm), max_heart_rate(101.0 bpm), avg_cadence([invalid] rpm (255)), max_cadence([invalid] rpm (255)), total_training_effect([invalid] (255)), event_group([invalid] (255)), session_trigger(<SessionTrigger.activity_end: 0> (0)), swim_stroke([invalid] (255)), pool_length_unit([invalid] (255)), avg_temperature([invalid] (Temperature(invalid))), max_temperature([invalid] (Temperature(invalid))), unknown_81(0.0), avg_fractional_cadence([invalid] rpm (255)), max_fractional_cadence([invalid] rpm (255)), total_fractional_cycles([invalid] cycles (255)), unknown_109([invalid] (255)), sport_index([invalid] (255)), unknown_147([invalid] (255)), unknown_148([invalid] (255)), unknown_149([invalid] (255)), min_temperature([invalid] (Temperature(invalid))), unknown_184(0.0), unknown_194([invalid] (255)), unknown_195(50.0)]): 'UnknownEnumValue' object has no attribute 'preferred'
> ```

If you share the FIT file that caused the above error, I can support for the missing fields. Share via some file sharing service.

**Comment by tcgoetz** [comment]
@lpierron commit f015af5c3403584b876bba2b65251f92ee418b95 adds support for your FIT file

**Comment by laurapoggio-sptools** [comment]
> I did it manually. I am trying again.

I managed to recreate the dbs without errors. Thanks

**Comment by tcgoetz** [comment]
> I managed to recreate the dbs without errors. Thanks

Does the BB data in the dbs meet your needs?

**Comment by laurapoggio-sptools** [comment]
yes. Perfect. Thanks!

**Comment by tcgoetz** [comment]
I'll release it once I've gathered up enough other changes to make a release.
