### ISSUE TITLE
venv: error: unrecognized arguments: --upgrade-deps

### ISSUE THREAD

**Issue by lpierron** [tcgoetz/GarminDB#140]
On a fresh `devel` branch when you run `make setup`, you get an error. If you create `.venv` before running `make setup`it's OK.

```
make setup

python3 -m venv --upgrade-deps /Users/pierron/Developpements/GARMIN/GarminDB/.venv
usage: venv [-h] [--system-site-packages] [--symlinks | --copies] [--clear] [--upgrade] [--without-pip] [--prompt PROMPT] ENV_DIR [ENV_DIR ...]
venv: error: unrecognized arguments: --upgrade-deps
make: *** [/Users/pierron/Developpements/GARMIN/GarminDB/.venv] Error 2
```

**Comment by tcgoetz** [comment]
What version of Python and venv are you using?

It works for me with Python 3.9 and the venv built in to 3.9.

> orion:GarminDB_develop tgoetz$ python3 -m venv --upgrade-deps /Users/tgoetz/Projects/GarminDB_develop/.venv
> Requirement already satisfied: pip in ./.venv/lib/python3.9/site-packages (21.2.4)
> Collecting pip
>   Using cached pip-21.3.1-py3-none-any.whl (1.7 MB)
> Requirement already satisfied: setuptools in ./.venv/lib/python3.9/site-packages (58.1.0)
> Collecting setuptools
>   Downloading setuptools-59.6.0-py3-none-any.whl (952 kB)
>      |################################| 952 kB 10.3 MB/s
> Installing collected packages: setuptools, pip
>   Attempting uninstall: setuptools
>     Found existing installation: setuptools 58.1.0
>     Uninstalling setuptools-58.1.0:
>       Successfully uninstalled setuptools-58.1.0
>   Attempting uninstall: pip
>     Found existing installation: pip 21.2.4
>     Uninstalling pip-21.2.4:
>       Successfully uninstalled pip-21.2.4
> Successfully installed pip-21.3.1 setuptools-59.6.0

**Comment by lpierron** [comment]
My version was 3.8:
python3 --version
Python 3.8.2

**Comment by tcgoetz** [comment]
Looks like that option is only in 3.9+. I will look into other options:

> Changed in version 3.9: Add --upgrade-deps option to upgrade pip + setuptools to the latest on PyPI

**Comment by smros** [comment]
I got a new development environment up, but it appears to try for a version of fitfile that is not available.  Is there a way to get the newer versions?


Collecting ipykernel
  Using cached ipykernel-6.7.0-py3-none-any.whl (127 kB)
ERROR: Could not find a version that satisfies the requirement fitfile>=1.1.0 (from -r requirements.txt (line 9)) (from versions: 1.0.0, 1.0.1, 1.0.2, 1.0.3, 1.0.4, 1.0.5)
ERROR: No matching distribution found for fitfile>=1.1.0 (from -r requirements.txt (line 9))

**Comment by tcgoetz** [comment]
> I got a new development environment up, but it appears to try for a version of fitfile that is not available. Is there a way to get the newer versions?

To install garmindb and its dependent packages from a source tree, run `make reinstall_al`l at the top level directory.
