### ISSUE TITLE
trouble to run garmindb_cli 

### ISSUE THREAD

**Issue by llarbodiere** [tcgoetz/GarminDB#146]
**Describe the bug**
I installed the package and added the json file with my identifiers at the right place. I import the package and it works.
But when I run the garmindb_cli.py --all --download --import --analyze in my vs code command prompt, it just display the python code in a bloc note (I have an anaconda env with python installed in it).

I also tried to run the following in my jupyter notebook but he does not find the package:
`%run C:\Users\lucas\anaconda3\Lib\site-packages\garmindb\garmindb_cli.py --all --download --import --analyze`

**Expected behavior**
The data to be imported

**Comment by tcgoetz** [comment]
Looks like your on Windows.

What happens when you run it from a command prompt like `C:\Users\lucas\anaconda3\Bin\python.exe C:\Users\lucas\anaconda3\Lib\site-packages\garmindb\garmindb_cli.py --all --download --import --analyze`

Is C:\Users\lucas\anaconda3\Lib\site-packages\garmindb\garmindb_cli.py marked as executable?

Sounds similar to this: https://github.com/Microsoft/vscode/issues/9987

**Comment by llarbodiere** [comment]
It is so strange I don't have python.exe in the bin folder.
And I don't have the garmindb_cli.py folder. Maybe I should unistall and reinstall the library?

![image](https://user-images.githubusercontent.com/81327006/153621542-c9bb52bf-f81e-474f-a0cf-119d5fdc3c65.png)


I'll look at the vscode#9987 thanks

**Comment by tcgoetz** [comment]
python.exe doesn't come from garmindb, that's your python install. garmindb_cli.py  may be in a bin directory.

**Comment by deMathias** [comment]
For me garmindb_cli is available at:

**Comment by openelch** [comment]
@tcgoetz Hi~ I'm in China and If I turn off the VPN, it tell me"Failed to login!"
![1](https://user-images.githubusercontent.com/56159632/208301614-b8e40fe4-6b88-4bf7-ba0e-0cc08f8d000f.png)
If I turn on VPN. it give me the error lik this:
![image](https://user-images.githubusercontent.com/56159632/208301798-716568d2-866f-4a39-b9bd-69e0136eae96.png)
Could you point anything clue with this?

**Comment by tcgoetz** [comment]
old
