### ISSUE TITLE
Yearly summaries for non-monitoring years

### ISSUE THREAD

**Issue by j-paulus** [tcgoetz/GarminDB#147]
I've had Garmin devices quite long, starting with an Edge and getting a wearable only a couple of years ago. The activities from the non-wearable time are in the DB, but the summary statistics tables are not created for these years for which no monitoring data is available. This makes partly sense, as there is no health monitoring data available. Still, it would be nice to have the activity summaries also for these years.

It seems that this could be (partly?) accomplished by modifying `garmindb/analyze.py/summary()` to use `years = Activities.get_years(self.garmin_act_db)` instead of `years = Monitoring.get_years(self.garmin_mon_db)`. Probably even more robust alterative is to take the union of these two tuples.

The drawback is that the summary tables contain `None` for the fields related to monitoring, and checking for the missing values needs to be added in the routines making use of these, e.g., in the jupyter notebooks.

**Comment by tcgoetz** [comment]
What data are you looking to get for activities only years? I see three columns that would be populated: activities, activities_calories, and activities_distance.  Is that what your looking for?

**Comment by tcgoetz** [comment]
Released
