### ISSUE TITLE
GarminConnectConfig.json not found

### ISSUE THREAD

**Issue by sunshineRunner22** [tcgoetz/GarminDB#149]
I'm using GarminDB on Windows 10 with Anaconda.
I'm getting an error when I run the following command (or any other command with garmindb_cli.py):  
_C:\Anaconda3\Scripts>python garmindb_cli.py --help_

Error:
_Missing config: copy GarminConnectConfig.json.example from C:\Anaconda3\lib\site-packages\garmindb to C:\Users\Admin\\.GarminDb\GarminConnectConfig.json and edit it to add your Garmin Connect username and password._

The _GarminConnectConfig.json_ is already in the specified folder (_C:\Users\Admin\\.GarminDb_). Any ideas?

**Comment by tcgoetz** [comment]
Couple of guesses:

- Config is present, but not readable: permission issue or invalid JSON

**Comment by sunshineRunner22** [comment]
The permissions exist and I just copied the original JSON without any changes (I don't need the online download, I'd just like to read in local files from the watch).

**Comment by sunshineRunner22** [comment]
I forgot to mention the first part of the error message:

_**Expecting value: line 33 column 43 (char 1137)**
Missing config: copy GarminConnectConfig.json.example from C:\Anaconda3\lib\site-packages\garmindb to C:\Users\Admin\\.GarminDb\GarminConnectConfig.json and edit it to add your Garmin Connect username and password.**_

**Comment by sunshineRunner22** [comment]
I found the reason for the error, the "modes"-part of the example JSON has no content:

    "modes": {
    }

After changing it to

    "modes": {
        "ignore_dev_fields"             : false
    }

it works fine.

But the last part of the JSON also throws the same error:

    "activities": {
        "display"                       : None
    }

What would be a valid entry for the "activities"-part? Thank you!

**Comment by tcgoetz** [comment]
empty modes should be fine. My config has an empty modes dictionary.

You can try:

    "display"                       : []

**Comment by tcgoetz** [comment]
Upgrade your garmindb. In the latest that error starts with "Missing or bad config" and has a line with more information about the error on the previous line.

**Comment by sunshineRunner22** [comment]
That works, thank you!
