### ISSUE TITLE
Class field `default_display_activities` is overridden to be a class method which then references itself

### ISSUE THREAD

**Issue by mbdevpl** [tcgoetz/GarminDB#154]
**Describe the bug**
I've just installed the package so forgive me if I missed something, but I think the class field `default_display_activities` is overridden to be a class method, but that won't work as the method is then referring to itself instead of referring to the field from parent class as intended.

The affected file (https://github.com/tcgoetz/GarminDB/blob/develop/garmindb/config_manager.py#L269):
```python3
    @classmethod
    def default_display_activities(cls):
        """Return a list of the default activities to display."""
        return [Sport.strict_from_string(activity) for activity in cls.default_display_activities]
```

And in parent class (https://github.com/tcgoetz/GarminDB/blob/develop/garmindb/config.py#L62):
```python3
    default_display_activities = ['walking', 'running', 'cycling']
```

**To Reproduce**
1. Run the `/Jupyter/activities.ipynb` notebook.
2. Execute the 1st (the only) cell.
3. See error

```
Traceback (most recent call last):
  File "/home/user/Software/Spack/opt/spack/linux-ubuntu20.04-skylake/gcc-10.0.1/python-3.8.5-vh56wykoxlpi2khoe3f5srsadhihgdvb/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3369, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "/tmp/ipykernel_229187/1108621078.py", line 78, in <cell line: 78>
    for display_activity in gc_config.display_activities():
  File "/home/user/Software/Spack/opt/spack/linux-ubuntu20.04-skylake/gcc-10.0.1/python-3.8.5-vh56wykoxlpi2khoe3f5srsadhihgdvb/lib/python3.8/site-packages/garmindb/garmin_connect_config_manager.py", line 115, in display_activities
    activities_list = ConfigManager.default_display_activities()
  File "/home/user/Software/Spack/opt/spack/linux-ubuntu20.04-skylake/gcc-10.0.1/python-3.8.5-vh56wykoxlpi2khoe3f5srsadhihgdvb/lib/python3.8/site-packages/garmindb/config_manager.py", line 268, in default_display_activities
    return [Sport.strict_from_string(activity) for activity in cls.default_display_activities]
TypeError: 'method' object is not iterable

During handling of the above exception, another exception occurred:

(...)
```

**Expected behavior**
I think the summary of all activities should be displayed in that notebook.

**Logs**
I can attach logs/info later if that's relevant, but from what I can tell it's clearly a bug in the codebase.

Using Python 3.8.5, on Ubuntu 20.04 x64, GarminDB 3.2.4 (latest from pypi) - but I can see the same issue is on master & develop branches on GitHub.

**Additional context**
I would submit a PR but not sure what is the best fix here as I'm not so familiar yet with the codebase.

I'd recommend one of:
1. not overriding a field into a method of the same name, maybe add a `get_*` prefix as with other methods in that subclass or rename the method entirely, as from what's going on inside it returns the list of sports (i.e. activity types) and not list of activities?
2. as a super quick and dirty fix, use `[Sport.strict_from_string(activity) for activity in super().default_display_activities]` instead of `[Sport.strict_from_string(activity) for activity in cls.default_display_activities]`

**Comment by fnicolaim** [comment]
As you said it seems that a simple change within the class method default_display_activities so that it calls a renamed property default_display_activities can be enough. I just changed the list within the options file from default_display_activities into _default_display_activities and applied the corresponding renaming within the class method.

**Comment by tcgoetz** [comment]
v3.3.1
