### ISSUE TITLE
Failed to login problem

### ISSUE THREAD

**Issue by openelch** [tcgoetz/GarminDB#167]
@tcgoetz Hi~ I'm in China and If I turn off the VPN, it tell me"Failed to login!"
![1](https://user-images.githubusercontent.com/56159632/208301614-b8e40fe4-6b88-4bf7-ba0e-0cc08f8d000f.png)
If I turn on VPN. it give me the error lik this:
![image](https://user-images.githubusercontent.com/56159632/208301798-716568d2-866f-4a39-b9bd-69e0136eae96.png)
Could you point anything clue with this?

**Comment by tcgoetz** [comment]
This project connects https://connect.garmin.com. Do you use the same website in China or is there a Chinese version?

**Comment by matin** [comment]
@tcgoetz With Garth, you can set the base domain with `garth.configure(domain="garmin.cn")`. There are people using Garth from China through this configuration.

**Comment by tcgoetz** [comment]
I added a config value for Garmin base domain.

**Comment by tcgoetz** [comment]
https://github.com/tcgoetz/GarminDB/releases/tag/v3.5.0
