### ISSUE TITLE
Password escaping issue

### ISSUE THREAD

**Issue by jbrechtel** [tcgoetz/GarminDB#169]
**Describe the bug**
When a password contains special characters then login may fail.

**To Reproduce**
1. Change your Garmin Connect password to include a "?" in it
2. Put that password in your GarminDb config file
3. Attempt to download activities or data using GarminDb
4. See that login fails

**Expected behavior**
Login should succeed

**Additional context**
I believe you may need to perform URL escaping on the params included in the `get` operation here https://github.com/tcgoetz/GarminDB/blob/master/garmindb/download.py#L122  but I'm not positive, it's only a hunch.

Once I changed my password to not include any special characters then login worked. Note I had all of "?;#^+" in my password before.

**Comment by tcgoetz** [comment]
I'll look into it. The password isn't passed as query params on 122, its passed as data on 134. The Python requests module should handle things like URL encoding, but this could be a Garmin API issue.

**Comment by tcgoetz** [comment]
How is your password passed? Is your password in the config or in a secure store?

**Comment by tcgoetz** [comment]
Any chance your password had a quotation mark in it?

**Comment by tcgoetz** [comment]
login is now done through an external library in https://github.com/tcgoetz/GarminDB/releases/tag/v3.5.0 Closing bugs filed against the old login code.
