### ISSUE TITLE
`bash` path doesn't work on macOS

### ISSUE THREAD

**Issue by saiwing-yeung** [tcgoetz/GarminDB#170]
**Describe the bug**
Rebuilding the db results in a "Command not found" error.

**To Reproduce**

```
make rebuild_dbs
fitbit.py --rebuild_db
make: /usr/local/bin/bash: Command not found
make: /usr/local/bin/bash: Command not found
make: /usr/local/bin/bash: No such file or directory
make: *** [rebuild_fitbit] Error 1
```

**Expected behavior**
Database get rebuilt.

**Additional context**
Modifying `defines.mk` like this fixes it on macOS, but it'd probably break other platforms.
```
diff --git a/defines.mk b/defines.mk
index 5102004..acc8b2c 100644
--- a/defines.mk
+++ b/defines.mk
@@ -10,13 +10,13 @@ PLATFORM=$(shell uname)

 ifeq ($(PLATFORM), Linux)

-SHELL=/usr/bin/bash
+SHELL=/bin/bash
 TIME ?= $(shell which time)
 YESTERDAY = $(shell date --date yesterday +"%m/%d/%Y")

 else ifeq ($(PLATFORM), Darwin) # MacOS

-SHELL=/usr/local/bin/bash
+SHELL=/bin/bash
 TIME ?= time
 YESTERDAY = $(shell date -v-1d +"%m/%d/%Y")
```

**Comment by tcgoetz** [comment]
If you're on MacOS uname should return Darwin and you should be in the

**Comment by saiwing-yeung** [comment]
Interesting... I am on 12.6.2 (21G320). For me, almost everything on `/usr/local/bin/` is from HomeBrew. From [this](https://www.cyberciti.biz/faq/change-default-shell-to-bash-on-macos-catalina/), I think all stock shells should be on `/bin`.
