### ISSUE TITLE
Can't login when installing via Source

### ISSUE THREAD

**Issue by kaliavarun** [tcgoetz/GarminDB#175]
**Describe the bug**
The command `make create_dbs` fails with the "failed to login!" error message.
Followed the instructions mentioned [here](https://github.com/tcgoetz/GarminDB#from-source).

**To Reproduce**
1. Cloned the project with ssh.
2. Executed `make setup` successfully.
3. Copied the GarminConnectConfig.json.example file from GarminDB/garmindb to GarminDB/ directory.
4. Changed the username and password in the JSON file.
4. Executed `make create_dbs`

The username/password are ok as I tested them on garmin connect portal and just copy/pasted from password manager.

**Expected behavior**
Data should be downloaded

**Actual with Logs**
<img width="392" alt="error" src="https://user-images.githubusercontent.com/8238649/221418752-0c7bd069-d189-404f-b91b-679f8b7b3f1b.png">

**Comment by tcgoetz** [comment]
This line:

`Copy GarminConnectConfig.json.example to ~/.GarminDb/GarminConnectConfig.json`

measn to copy the example to a directory named .GarminDb in your home directory. In my case that directory is:

```
(.venv) orion:GarminDB_develop tgoetz$ ls /Users/tgoetz/.GarminDb/
GarminConnectConfig.json
```

**Comment by kaliavarun** [comment]
> This line:
> 
> `Copy GarminConnectConfig.json.example to ~/.GarminDb/GarminConnectConfig.json`
> 
> measn to copy the example to a directory named .GarminDb in your home directory. In my case that directory is:
> 
> ```
> (.venv) orion:GarminDB_develop tgoetz$ ls /Users/tgoetz/.GarminDb/
> GarminConnectConfig.json
> ```

Thanks a lot. I didn't notice that. It works now.
