### ISSUE TITLE
Error: No module named 'numpy.core._multiarray_umath'

### ISSUE THREAD

**Issue by Molleke** [tcgoetz/GarminDB#180]
**Describe the bug**
ImportError:

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.10 from "/opt/bin/python3"
  * The NumPy version is: "1.24.3"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: No module named 'numpy.core._multiarray_umath'

**To Reproduce**
Just ran  garmindb_cli.py --help

**Comment by tcgoetz** [comment]
Is this repeatable with the current release https://github.com/tcgoetz/GarminDB/releases/tag/v3.4.0 ?
