### ISSUE TITLE
no name value in field 'activities.name' if subsport is cardio

### ISSUE THREAD

**Issue by lorenzovercruysse** [tcgoetz/GarminDB#181]
Hi, first of all thanks for putting an effort in this great and open-source tool! I'm new so I'm not aware of any conventioning. But I'm glad to give my support in the abilities I have. Therefore I'll be looking out for some issues I come across and report them here.

**Describe the bug**
In the table 'activities', records with sub_sport 'cardio_training' have a NULL value in the field 'name', while there is a name on the activity.

**To Reproduce**
1. Create an activity on garmin connect with activity type 'cardio', make sure it has a name.
2. import latest data through script
3. open sqlite db 'garmin_activities' and query 'select * from activities where sub_sport = 'cardio_training'
4. See the value in field 'name'

**Expected behavior**
The name of the activity represented in the table.field 'activities.name'

**Comment by alexis-m** [comment]
Huh, I checked my db, and the following `sport/sub_sport` activities have NULL in the `name` column: `training/cardio_training`, `kayaking/generic`, `stand_up_paddleboarding/generic`.

I can see that Garmin Connect web sites shows the names, and that the downloaded json files for the corresponding activities have the `activityName` field. I haven't checked the downloaded fit files yet.

**Comment by tcgoetz** [comment]
commit 8c521a52aa54247ccfa8dc75a93ea7fa65355aa0

**Comment by tcgoetz** [comment]
Fenix 7 support: https://github.com/tcgoetz/Fit/commit/f7e1d799e307eaa2221719530a681ef9796bf7f0

**Comment by tcgoetz** [comment]
fixed in: https://github.com/tcgoetz/GarminDB/releases/tag/v3.4.0
