### ISSUE TITLE
Unable to start program

### ISSUE THREAD

**Issue by jhavens12** [tcgoetz/GarminDB#2]
When using the expected input 

`make GC_DATE=01/01/2018 GC_DAYS=10 GC_USER=username GC_PASSWORD=password scrape_monitoring`

I get the response:

```
python scrape_garmin.py -d 01/01/2018 -n 10 -u username -p password  -m "/Users/USERNAME/HealthData/FitFiles/Incoming"
Missing arguments:
scrape_garmin.py -d [<date> -n <days> | -l <path to dbs>] -u <username> -p <password> [-m <outdir> | -w <outdir>]
  -d <date ex: 01/21/2018> -n <days> fetch n days of monitoring data starting at date
  -l check the garmin DB and find out what the most recent date is and fetch monitoring data from that date on
  -m <outdir> fetches the daily monitoring FIT files for each day specified, unzips them, and puts them in outdit
  -w  fetches the daily weight data for each day specified and puts them in the DB
```
I can't seem to get around this, all of the arguments are filled out as far as I can tell. Thanks

**Comment by tcgoetz** [comment]
I'll commit a fix for this tonight.

**Comment by jhavens12** [comment]
Thanks!

**Comment by tcgoetz** [comment]
commit 126cad2, please reply with success/failure

**Comment by benbowen** [comment]
seems to be working since the update (minutes ago).  opened a firefox browser and is downloading content from site for days specified.

**Comment by jhavens12** [comment]
When I run the same command, I now get a different response:

```
python scrape_garmin.py -d 01/01/2018 -n 10 -u USER-p PASSWORD  -m "/Users/Havens/HealthData/FitFiles/Incoming"
No handlers could be found for logger "scrape_garmin.py"
Traceback (most recent call last):
  File "scrape_garmin.py", line 308, in <module>
    main(sys.argv[1:])
  File "scrape_garmin.py", line 290, in main
    scrape = Scrape()
  File "scrape_garmin.py", line 43, in __init__
    self.browser = webdriver.Firefox(firefox_profile=fp, executable_path=geckodriver)
  File "/Library/Python/2.7/site-packages/selenium/webdriver/firefox/webdriver.py", line 142, in __init__
    self.service.start()
  File "/Library/Python/2.7/site-packages/selenium/webdriver/common/service.py", line 81, in start
    os.path.basename(self.path), self.start_error_message)
selenium.common.exceptions.WebDriverException: Message: 'geckodriver' executable needs to be in PATH. 

Exception AttributeError: "Scrape instance has no attribute 'browser'" in <bound method Scrape.__del__ of <__main__.Scrape instance at 0x10fccae18>> ignored
make: *** [scrape_monitoring] Error 1
```

I have geckodriver installed and it is in path, i can just type "geckodriver" into terminal and it begins. I even made sure it was located in /usr/local/bin/

To compare, i used the other command I was previously commenting on:

`make GC_USER=USER GC_PASSWORD=PW`

and the result is that the program begins to scrape for 2/14/17 (a year ago) but there is a pop-up that says there is no data to export. I assume this should work if the first command is successful and begins to build the database and then this second command just builds on top of it?

Thank you for your continued work on this, I would really love for this to work

**Comment by tcgoetz** [comment]
Right now the code assumes geckodriver is installed in a directory 'bin' under the directory where the script is run. 'make deps' installs geckodriver in GarminDB/bin so it is available to any script run in GarminDB.

scrape_garmin.py line 41:

        geckodriver = os.getcwd() + "/bin/geckodriver"
        logger.info("Creating driver")
        self.browser = webdriver.Firefox(firefox_profile=fp, executable_path=geckodriver)

**Comment by jhavens12** [comment]
Thanks for that, i ran the make deps again which placed geckodriver in the right spot.

When running the above command, I now get the following results:

```
mkdir -p /Users/Havens/HealthData/DBs
mkdir -p /Users/Havens/HealthData/FitFiles/2018_Monitoring
python scrape_garmin.py -d 01/01/2018 -n 10 -u USER -p PW  -m "/Users/Havens/HealthData/FitFiles/Incoming"
No handlers could be found for logger "scrape_garmin.py"
Traceback (most recent call last):
  File "scrape_garmin.py", line 309, in <module>
    main(sys.argv[1:])
  File "scrape_garmin.py", line 293, in main
    scrape.get_monitoring(date, days)
  File "scrape_garmin.py", line 145, in get_monitoring
    self.browse_daily_page(profile_name, day_date)
  File "scrape_garmin.py", line 133, in browse_daily_page
    page_container = self.wait_for_pagecontainer(self.browser, 10)
  File "scrape_garmin.py", line 101, in wait_for_pagecontainer
    return self.wait_for_xpath(driver, time_s, "//div[@id='pageContainer']")
  File "scrape_garmin.py", line 97, in wait_for_xpath
    return WebDriverWait(driver, time_s).until(EC.presence_of_element_located((By.XPATH, xpath)))
  File "/Library/Python/2.7/site-packages/selenium/webdriver/support/wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 

make: *** [scrape_monitoring] Error 1
```
It looks like it creates the folders and runs through the website for the specified date and then errors out. It creates the folder structure but does not actually grab anything? 

```
COMPUTER:HealthData USER$ ls -lh *
DBs:

FitFiles:
total 0
drwxr-xr-x  2 USER  staff    64B Feb 14 07:57 2018_Monitoring
```

**Comment by jhavens12** [comment]
to confirm, the command that I had run is:

`make GC_DATE=01/01/2018 GC_DAYS=10 GC_USER=USER GC_PASSWORD=PW scrape_monitoring`

**Comment by tcgoetz** [comment]
It timed out here:

     self.wait_for_xpath(driver, time_s, "//div[@id='pageContainer']")

which is waiting for a particular element to appear in the webpage. What did you see in the browser? It should be on the "Daily Summary" page for the day to download. After that it is looking for the gear icon in the upper right which it clicks to get to the 'Export Original' button which it clicks. In your case it's waiting for the base page container to appear and times out waiting for it.

**Comment by jhavens12** [comment]
I ran it again and watched it more closely this time and for some reason this time it completed without error. Then according to your README I am supposed to run

`make import_monitoring`

When I did this, the result was:

```
python import_garmin_fit.py -e --input_dir "/Users/Havens/HealthData/FitFiles/2017_Monitoring" --sqlite /Users/Havens/HealthData/DBs
Traceback (most recent call last):
  File "import_garmin_fit.py", line 10, in <module>
    import Fit
ImportError: No module named Fit
make: *** [import_monitoring] Error 1
```
I do have the fit files in the "incoming" folder and I have an empty 2018_Monitoring folder, but do not have the 2017_Monitoring folder as my specified date was 01/01/2018 - not sure how to correct this?

Thanks!

**Comment by tcgoetz** [comment]
Your running into issue #4 now. Run `make update` to clone the Fit submodule. Right now you have a Fit subdirectory that is empty..

**Comment by jhavens12** [comment]
This is now resolved and works as expected
