### ISSUE TITLE
cannot download data from garmin

### ISSUE THREAD

**Issue by EmptySoft** [tcgoetz/GarminDB#202]
installed package garmindb 3.5.0, installed using Python 3.11.5

when i try to run
`/usr/bin/garmindb_cli.py --all --download --import --latest`

i get
`___Downloading Latest Data___
Traceback (most recent call last):
  File "/usr/bin/garmindb_cli.py", line 358, in <module>
    main(sys.argv[1:])
  File "/usr/bin/garmindb_cli.py", line 339, in main
    download_data(args.overwrite, args.latest, args.stats)
  File "/usr/bin/garmindb_cli.py", line 112, in download_data
    if not download.login():
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/garmindb/download.py", line 166, in login
    self.display_name = self.user_prefs['displayName']
                        ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
`

**Comment by tcgoetz** [comment]
That looks like the stack from the failure that 3.5 fixed.

**Comment by EmptySoft** [comment]
Hi Tom.! 
Which 3.5 do you mean? I have GarminDB 3.5 installed.

**Comment by EmptySoft** [comment]
OK, i have done a upgrade via 
`pip install --upgrade garmindb`
now i get
`kalymnos:~> /usr/bin/garmindb_cli.py --all --download --import --latest
Traceback (most recent call last):
  File "/usr/bin/garmindb_cli.py", line 28, in <module>
    from garmindb import GarminProfile, GarminWeightData, GarminSummaryData, GarminMonitoringFitData, GarminSleepFitData, GarminSleepData, GarminRhrData, GarminSettingsFitData, \
ImportError: cannot import name 'GarminProfile' from 'garmindb' (/home/harald/.local/lib/python3.11/site-packages/garmindb/__init__.py)
`

**Comment by Preliator-code** [comment]
Oh yes ! i  had the same issue. I fixed that in download.py
![2023-10-10_090716](https://github.com/tcgoetz/GarminDB/assets/46316410/5e35288e-644a-41f5-97c2-513d6cf299b9)

**Comment by tcgoetz** [comment]
An import error like that sounds like a mismatch between the version of the cli and the rest of the package. I don't have access to a computer right now to check the actual commands, but I would uninstall and then reinstall GarminDb.

**Comment by EmptySoft** [comment]
Hi Tom.!

Thank you so much, after uninstall all garmindb Files and new clean install it works

Thanks, Harald
