### ISSUE TITLE
cannot import name 'Graph' from 'garmindb'

### ISSUE THREAD

**Issue by joapim1** [tcgoetz/GarminDB#211]
Running the jupyter notebook summary fails.

There seems like there is no file named Graph in garmindb. All the other jupyter notebooks work fine.

To Reproduce
1. Open the jupyter notebook  named summary
2. Run the code
4. Fails with the import error: cannot import name 'Graph' from 'garmindb' (C:\Users\xxx\AppData\Local\Programs\Python\Python310\lib\site-packages\garmindb\__init__.py)

**Comment by tcgoetz** [comment]
The fix is on the develop branch.
