### ISSUE TITLE
Unclear what python version is required

### ISSUE THREAD

**Issue by thebigredorb** [tcgoetz/GarminDB#218]
**Describe the bug**
Documentation error: It is unclear what Python version is required. setup.py indicates >= 3.0. READNE.md sais 3.x. Success stories seems to indicate that 3.8+ works. But my experience is that 3.9 is required, due to the usage of venv option "-upgrade-deps", which was introduced in 3.9

**To Reproduce**
Run make setup with python < 3.9

**Expected behavior**
README.md and setup.py could indicate a more precise python version requirement. 

**Logs**

**Please run bugreport.sh and attach bugreport.zip.**

**Additional context**

This is of course only a small inconvenience, but it can take som time to figure out. Thanks for your great work :)

**Comment by tcgoetz** [comment]
`make setup` now checks the version of python vs whats required for development.
