### ISSUE TITLE
ImportError: No module named request

### ISSUE THREAD

**Issue by Saralkarki** [tcgoetz/GarminDB#22]
Hi,
I've been trying to extract the Garmin data and here's the error I received.
My command 

`make GC_DATE='01/10/2018' GC_DAYS=150 GC_USER=saral.karki GC_PASSWORD=password create_dbs`

And the error I get

`Traceback (most recent call last):
  File "download_garmin.py", line 8, in <module>
    import requests
ImportError: No module named requests
make: *** [download_monitoring] Error 1`

What am I doing wrong? 

I tried running `pip install requests` but I get a message saying `requirement already satisfied`.

**Comment by tcgoetz** [comment]
Did you run `make setup` ? `make setup` should result in the makefile target "install_deps" running which installs the requests python moduule: https://github.com/tcgoetz/GarminDB/blob/b327b9ab0fc737db7faceda8d5632ba53d3975b5/Makefile#L106

**Comment by tcgoetz** [comment]
> I tried running pip install requests but I get a message saying requirement already satisfied.

This sounds like problem with your Python environment. What is your environment? OS? Python version?

**Comment by Saralkarki** [comment]
I did run make setup. My setup
- Mac OS Mojave, version 10.14.3
- 2.7.10 [GCC 4.2.1 Compatible Apple LLVM 10.0.0 (clang-1000.0.42)]

And as soon I had done this I realised I was in the wrong environment. I don't remember switching to an older version of python, I thought I was still using Python 3. 

I got it working now. Thanks for the troubleshoot. :)
