### ISSUE TITLE
Feature request: Add support for Training Status/Training Load

### ISSUE THREAD

**Issue by shemeshg** [tcgoetz/GarminDB#221]
**Is your feature request related to a problem? Please describe.**

Hi, I am a user of GarminDB and I would like to request a feature to add support for Training Status. Training Status is a feature that shows how training affects fitness level and performance. It is based on changes to training load and VO2 max. over an extended time period. 

However, GarminDB does not seem to support this feature yet. It does not extract the Training Status information from the FIT files, and it does not exists in the JSON files, . or sqlite tables or sqlite views.

 I would like to be able to access this information from the database and build a graph from it.

**Describe the solution you'd like**
Is it possible to add this feature to GarminDB? 
I think it would be very useful for many users who want to monitor their training status and improve their performance.

**Describe alternatives you've considered**
N/A

**Additional context**
I think it might be a two week moving calculation, and it is not actually save in fit files. however it might be possible to linear regress.

**Comment by tcgoetz** [comment]
Is this data available in the currently downloaded JSON or FIT files? If so where? If not, where is it available?

**Comment by shemeshg** [comment]
I'm not sure. I searched it all and found none (using `grep` and sqlite schema).

Here is a snapshot from "Garmin Connect" "All Activities" "Training Status" "Active Training Load"

![Screenshot 2024-02-05 at 18 55 35](https://github.com/tcgoetz/GarminDB/assets/8200598/9700be87-945d-43c3-a872-7ff271cb4f4c)

It also appears on the watch itself as "Training Status".

My wild guess is that it seems to be a regression where the dependent variables are "Intensity Minutes" and maybe "Recovery Time" (do we have recovery time?) ?

**Comment by tcgoetz** [comment]
commit 9171ee3 on develop branch: activities now have their training load

**Comment by tcgoetz** [comment]
Activities now include training load. You need to graph training load across recent activities to get the above graph. https://github.com/tcgoetz/GarminDB/releases/tag/v3.5.3

Let me know if you think there is more that can be done here.

**Comment by shemeshg** [comment]
THanks, this is greate
