### ISSUE TITLE
ERROR:root:Login failed: <!DOCTYPE html>

### ISSUE THREAD

**Issue by wechsler42** [tcgoetz/GarminDB#23]
Hi there,
first of all thanks for this great piece of Phyton scripts!
I used it for 11 days on Xubuntu Bionic LTS without any flaw. Yesterday I used without any issues, today I tried it again and now it throws errors. So I cloned the most recent version from github and started over but unfortuantely it throws the same errors. It starts with:
`make GC_DATE=2019-04-05 GC_DAYS=9 GC_USER=MyUserName GC_PASSWORD=MyPassWord create_dbs
mkdir -p /home/wechsler/HealthData/FitFiles/2019_Monitoring
python download_garmin.py -d 2019-04-05 -n 9 -u MyUserName -p MyPassWord -P "/home/wechsler/HealthData/FitFiles" -m "/home/wechsler/HealthData/FitFiles/2019_Monitoring"
INFO:root:Profile: /home/wechsler/HealthData/FitFiles
ERROR:root:Login failed: <!DOCTYPE html>
<html class="no-js">`

and ends with:
`INFO:root:Fetching 1000 activities
INFO:root:get_activity_types: '/home/wechsler/HealthData/FitFiles/Activities'
INFO:root:get_activities: '/home/wechsler/HealthData/FitFiles/Activities' (1000)
INFO:root:get_activity_summaries
Traceback (most recent call last):
  File "download_garmin.py", line 467, in <module>
    main(sys.argv[1:])
  File "download_garmin.py", line 419, in main
    download.get_activities(activities, activity_count, overwite)
  File "download_garmin.py", line 236, in get_activities
    for activity in activities:
TypeError: 'NoneType' object is not iterable
Makefile:247: recipe for target 'download_all_activities' failed
make: *** [download_all_activities] Error 1`
However, I doublechecked my Username and Password and it works on  Garmin Connnect without any issues. Perhaps you may have a hint for me how to get it working again? Thanks in advance, 
wechsler42

**Comment by tcgoetz** [comment]
Garmin has changed the login sequence and I'm going to have to work it out. Stay tuned.

**Comment by wechsler42** [comment]
Thank you very much tcgoetz for fixing the login issue that fast. It works now again flawlessly :-)
