### ISSUE TITLE
Cannot import name 'ConfigManager'

### ISSUE THREAD

**Issue by Forchio** [tcgoetz/GarminDB#232]
I've done a new installation of Python and GarminDB. When I try to import GarminDB, I have the error message : cannot import name 'ConfigManager'

**Comment by smacrico** [comment]
i am faching the exact same issue..

**Comment by lpierron** [comment]
It sounds like `ConfigManager` has been renamed:`GarminConnectConfigManager`

**Comment by mn-box** [comment]
Any resolution? I have been using GarminDB for some time, but now returning this error

![image](https://github.com/user-attachments/assets/dafca480-f4ec-4125-be8c-0a54d4abd1de)

Thanks!

**Comment by tcgoetz** [comment]
I'm not sure how you're getting that. The current release doesn't have any references to ConfigManager. First I'd try uninstalling and reinstalling the latest. If it reoccurs after that, please find exactly where your getting the reference to ConfigManager.

**Comment by mn-box** [comment]
Thanks Tom, that indeed did the trick!
