### ISSUE TITLE
Are dependency versions hard requirements, or the version that tests are done with?

### ISSUE THREAD

**Issue by Grimler91** [tcgoetz/GarminDB#235]
**Is your feature request related to a problem? Please describe.**
requirements.txt at the moment contains 

```
SQLAlchemy==2.0.27
python-dateutil==2.8.2
cached-property==1.5.2
tqdm==4.66.2
garth>=0.4.44
fitfile>=1.1.7
tcxfile>=1.0.4
idbutils>=1.1.0
```

Are there features in SQLAlchemy 2.0.27 that are required, or could perhaps SQLAlchemy 1.4.X, or >= 2.0.0, work as well?

Basically I am wondering if versions are connected to features/big fixes or whether versions are set to match what you have on your system, and hence test with?

In particular SQLAlchemy > 2.0.0 seems to not have made it into many distros yet, [looking at repology only a handful has it](https://repology.org/project/python:sqlalchemy/versions), so if 2.0.27 is a hard requirement then it is difficult to install GarminDB in most distros (but of course possible with pip and virtual python environments).

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by tcgoetz** [comment]
Definitely the version that was tested. In some cases their are feature requirements.

**Comment by tcgoetz** [comment]
Teh recommended install is with pip in a virtual environment.

**Comment by Grimler91** [comment]
Thanks, that clears it up!
