### ISSUE TITLE
make: *** [import_weight] Error 1

### ISSUE THREAD

**Issue by wechsler42** [tcgoetz/GarminDB#24]
Sorry tcgoetz, it is me again ...
With the latest built from today I face an error message I did not have before. I just post the very end of it, just let me know if you need more information:
`python import_garmin.py --weight_input_dir "/home/wechsler/HealthData/Weight" --sqlite /home/wechsler/HealthData/DBs
INFO:GarminDB.GarminDB:GarminDB: {'db_type': 'sqlite', 'db_path': '/home/wechsler/HealthData/DBs'} debug: False 
INFO:import_garmin.py:Debug: 0 English units: False
INFO:/home/wechsler/Downloads/FitMaster2/GarminDB/FileProcessor.pyc:Reading directory: /home/wechsler/HealthData/Weight
INFO:import_garmin.py:Processing 38 weight files
INFO:GarminDB.GarminDB:GarminDB: {'db_type': 'sqlite', 'db_path': '/home/wechsler/HealthData/DBs'} debug: False 
Traceback (most recent call last):
  File "import_garmin.py", line 344, in <module>
    main(sys.argv[1:])
  File "import_garmin.py", line 325, in main
    gwd.process_files(db_params_dict)
  File "import_garmin.py", line 49, in process_files
    date_str = json_data['startDate']
TypeError: list indices must be integers, not str
Makefile:282: recipe for target 'import_weight' failed
make: *** [import_weight] Error 1`
Thanks in advance for helping this error disappear.

**Comment by wechsler42** [comment]
Hi tcgoetz,
just a further finding, I can avoid this issue when I start all over with:
`make GC_DATE=<date to start scraping monitoring data from> GC_DAYS={number of days of monitoring data to download} GC_USER={username} GC_PASSWORD={password} create_dbs`

**Comment by wechsler42** [comment]
Hi there,  
thanks for the new built 59cabbf .
I applied it with the command ` make GC_USER={username} GC_PASSWORD={password}` on my data exported with built d94c9c2. Unfortunately, it yielded another error:
`INFO:GarminDB.GarminDB:GarminDB: {'db_type': 'sqlite', 'db_path': '/home/wechsler/HealthData/DBs'} debug: False 
INFO:root:Automatically downloading rhr data from: 2019-04-17
INFO:root:get_rhr: 2019-04-17 - 2019-04-18
INFO:root:get_rhr_day: 2019-04-17
INFO:root:get_rhr_day: 2019-04-18
python import_garmin.py --rhr_input_dir "/home/wechsler/HealthData/RHR" --sqlite /home/wechsler/HealthData/DBs
INFO:GarminDB.GarminDB:GarminDB: {'db_type': 'sqlite', 'db_path': '/home/wechsler/HealthData/DBs'} debug: False 
INFO:import_garmin.py:Debug: 0
INFO:/home/wechsler/Downloads/FitMaster2/GarminDB/FileProcessor.pyc:Reading directory: /home/wechsler/HealthData/RHR
INFO:import_garmin.py:Processing 2 rhr files
INFO:GarminDB.GarminDB:GarminDB: {'db_type': 'sqlite', 'db_path': '/home/wechsler/HealthData/DBs'} debug: False 
Traceback (most recent call last):
  File "import_garmin.py", line 360, in <module>
    main(sys.argv[1:])
  File "import_garmin.py", line 356, in main
    grhrd.process_files(db_params_dict)
  File "import_garmin.py", line 202, in process_files
    rhr_list = json_data['allMetrics']['metricsMap']['WELLNESS_RESTING_HEART_RATE']
KeyError: 'WELLNESS_RESTING_HEART_RATE'
Makefile:297: recipe for target 'import_rhr' failed
make: *** [import_rhr] Error 1`
I tried to export my data again with command ` make GC_USER={username} GC_PASSWORD={password}` with built d94c9c2 and it worked without any error.

**Comment by tcgoetz** [comment]
Does this still happen with the latest code?

**Comment by wechsler42** [comment]
Thanks a lot  tcgoetz for fixing the issue! I just made a test run with commit d2eb8d9  and everything works as intended :-)
