### ISSUE TITLE
make: *** No rule to make target `download_garmin', needed by `create_dbs'.  Stop.

### ISSUE THREAD

**Issue by gabefortin** [tcgoetz/GarminDB#25]
Any idea what I'm doing wrong, ran make setup, created/edited GarminConnectConfig.py and I get this when I run make create_dbs.
Thanks!

**Comment by tcgoetz** [comment]
Fixed. Run `make setup` and run again. (966f1e9dcb2f38d44bf196d08938bc84bd3c76ef)

**Comment by gabefortin** [comment]
That did it, thanks!
