### ISSUE TITLE
how do I use the db files e.g. for comparing workouts?

### ISSUE THREAD

**Issue by claus-hultschig** [tcgoetz/GarminDB#29]
Sorry but I do not understand how to use the db files.
Is the an example case i could use as a guid?

**Comment by tcgoetz** [comment]
The *.db files are the Dbs. They are SQLite DB files: https://sqlite.org/about.html. You can browse them with a SQLite DB browser like the ones mentioned in the project page: https://github.com/tcgoetz/GarminDB -> https://sqlitestudio.pl/index.rvt?act=about. The first screenshot in the README.md  is using SQLiteStudio to browse the DB files.
