### ISSUE TITLE
garmin table devices version mismatch. The DB schema has been updated. Please rebuild the garmin DB.

### ISSUE THREAD

**Issue by sis9** [tcgoetz/GarminDB#30]
Hello, got an error again when trying to do make create_dbs. Is it something wrong with my databse in garmin connect or what?

![image](https://user-images.githubusercontent.com/47052536/59528250-0fc58e80-8ede-11e9-8904-713473b11c72.png)

Another question: what should be the right file pathway in defines for the the db files? (windows)

HEALTH_DATA_DIR=$/mnt/c/Users/Simon/Desktop/Ny/GarminDB/HealthData/
DB_DIR=$(HEALTH_DATA_DIR)/DBs
BACKUP_DIR=$(HEALTH_DATA_DIR)/Backups

**Comment by tcgoetz** [comment]
DB schema mismatch means that the GarminDB code has been updated in a way that changes the DB layout. You need to rebuild the Dbs from your downloaded data files. You do that with `make rebuild_dbs`.

There is no "right" place for the Dbs. Where do you want them to be?

Your running GarminDB on the Windows Ubuntu subsystem? /mnt/c/Users/Simon/Desktop/Ny/GarminDB/HealthData/ seems reasonable.
