### ISSUE TITLE
No Sleep, Weight, RHR data

### ISSUE THREAD

**Issue by christian-ho** [tcgoetz/GarminDB#34]
I have a problem with Sleep, RHR, Weight and Calories Data.

The data is only created for the first day specified in die GarminConnectConfig.json

There is also just 1 json file in the respective directories (/healthdata/RHR ...) and only 1 daily summary json.

hrmin, hrmax, steps ...  on the other hand, work perfectly.

**Comment by tcgoetz** [comment]
Can you run bugreport.sh and send me the zip it creates?

**Comment by christian-ho** [comment]
I think there is a problem with your bugreport.sh, as `${PYTHON} garmin.py --version >> ${BUGREPORT}` overwrites the garmin.log file, or is this an intended behavior?

[bugreport_1574927121.zip](https://github.com/tcgoetz/GarminDB/files/3900513/bugreport_1574927121.zip)

**Comment by christian-ho** [comment]
I just made another run for a complete log file:
[garmin.zip](https://github.com/tcgoetz/GarminDB/files/3900708/garmin.zip)

**Comment by tcgoetz** [comment]
Thanks for the bug report. I think I fixed it. Give it a try and let me know.

**Comment by christian-ho** [comment]
Many thanks, data is created as expected again.

There is however, a 404 HTTP error concerning sleep data, the sleep json files look like this:

`{"message": "HTTP 404 Not Found", "error": "NotFoundException"}`

**Comment by tcgoetz** [comment]
Please update to the latest and send me a log file if you can reproduce it. Thanks!

**Comment by christian-ho** [comment]
Now i'm getting the following exception when trying to download sleep data:

./garmin.py --sleep --download --import --analyze --overwrite
Traceback (most recent call last):
  File "/home/christian/Projekte/GarminDB/utilities/rest_client.py", line 105, in get response.raise_for_status()
  File "/home/christian/.local/lib/python3.6/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://connect.garmin.com/modern/proxy/wellness-service/wellnessproxy/dailySleepData/6f5b0849-0dd4-4318-8547-a4134b12bfad?date=2019-07-13

**Comment by tcgoetz** [comment]
Fixed. Please try again.

**Comment by christian-ho** [comment]
Thanks for your quick fix, Tom, now it's working.

Btw ... any plans on including hydration data?

**Comment by tcgoetz** [comment]
I haven't looked ta hydration data yet, but I can probably do it. Would the daily summary for hydration be enough?

**Comment by christian-ho** [comment]
As there isn't really much to look at, that would be enough for me. 👍

**Comment by tcgoetz** [comment]
Can you file a new issue requesting the hydration support? I'm going to close this issue as fixed.
