### ISSUE TITLE
can not change HEALTH_DATA_DIR

### ISSUE THREAD

**Issue by laurentperrinet** [tcgoetz/GarminDB#36]
I have been changing `HEALTH_DATA_DIR` in `defines.mk` to another directory, but is stills saves data in `~/HealthData/`. I have tried many quirks but to no avail.

And .. Thanks a lot for your great library!

**Comment by tcgoetz** [comment]
That define was obsolete. The config is in garmin_db_config.py now. I've updated the Makefile to backup target to use the values form that file.
