### ISSUE TITLE
no module named Fit

### ISSUE THREAD

**Issue by benbowen** [tcgoetz/GarminDB#4]
I used your most recent commit to download my fit files into HealthData/FitFiles/Incoming, but get an error when going to next steps in the instructions:

```
> python import_garmin_fit.py -e --input_dir "HealthData/FitFiles/2017_Monitoring" --sqlite HealthData/DBs
Traceback (most recent call last):
  File "import_garmin_fit.py", line 10, in <module>
    import Fit
ImportError: No module named Fit
```

When I look at GarminDB/Fit on my computer, its empty.  On github, Fit in GarminDB is linked to a standalone repo.

Should I be doing something special, other than git clone, to force GarminDB to pull in the Fit module? I can manually git clone Fit.  Is there a better way?

**Comment by tcgoetz** [comment]
Fit is a git submodule. I just committed a change to check it (and any other submodules) out automatically with a make target 'make update'.

**Comment by benbowen** [comment]
I updated and pulled and did a make update,but Fit was still empty.  I manually cloned from your Fit repo.  I've never done submodules in git, but can learn it on my own.

I'm excited to see the DB come to life! Like @jhavens12 I'm seeing some odd behavior, and will follow closely the tickets and updates.

**Comment by benbowen** [comment]
There are so many pieces at play here I'm very impressed you were able to
stitch them all together.  Thanks so much for making and sharing this!

**Comment by jhavens12** [comment]
I tried the make update command to download the fit submodule - but the folder remained empty. I removed the Fit folder and then manually cloned the repo into a Fit folder

**Comment by tcgoetz** [comment]
This one surprises me. `make update` works me and it's a pattern that I've used in my work to.

What is your environment? OS? git version? I wonder if I installed a git extension long ago that I've forgotten about...

`make update1 should run `git submodule init` and then `git submodule update`. The later should check out the Fit repo.

**Comment by benbowen** [comment]
[bpb@Benjamins-MacBook-Pro-4 ~ 06:05 AM] ~/repos/garmin_activity/GarminDB
(master) > git --version

git version 2.14.3 (Apple Git-98)

**Comment by jhavens12** [comment]
Running OSX 10.13.2, git version 2.15.1
I set up a new folder, cloned the main repo, did make deps and this is the result of make update:

```
GarminDB Havens$ make update
git submodule init
Submodule 'Fit' (git@github.com:tcgoetz/Fit.git) registered for path 'Fit'
git submodule update
Cloning into '/Users/Havens/Documents/GitHub/test/GarminDB/Fit'...
The authenticity of host 'github.com (192.30.253.112)' can't be established.
RSA key fingerprint is SHA256:nThbg6kXUpJWGl7E1IGOCspRomTxdCARLviKw6E5SY8.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added 'github.com,192.30.253.112' (RSA) to the list of known hosts.
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:tcgoetz/Fit.git' into submodule path '/Users/Havens/Documents/GitHub/test/GarminDB/Fit' failed
Failed to clone 'Fit'. Retry scheduled
Cloning into '/Users/Havens/Documents/GitHub/test/GarminDB/Fit'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:tcgoetz/Fit.git' into submodule path '/Users/Havens/Documents/GitHub/test/GarminDB/Fit' failed
Failed to clone 'Fit' a second time, aborting
make: *** [submodules_update] Error 1
```

**Comment by tcgoetz** [comment]
On the surface that seems like a GitHub issue. How did you clone the GarminDB repo? Do you have ssh key access setup for GitHub?

**Comment by jhavens12** [comment]
I just used

`git clone https://github.com/tcgoetz/GarminDB.git`

I dont have ssh keys setup, I've never seen that before which is strange. I can try again later to see if it was just a github hiccup

**Comment by tcgoetz** [comment]
I use:

    git clone git@github.com:<git hub username>/GarminDB.git
