### ISSUE TITLE
No rule to make target error

### ISSUE THREAD

**Issue by olddawgpowers** [tcgoetz/GarminDB#42]
I am trying to get older data for weight and trying to use make download_weight and get the following? 
pi@raspberrypi:~/GarminDB $ make download_weight
make: *** No rule to make target 'download_weight'.  Stop.
pi@raspberrypi:~/GarminDB $ 

I was able to get data by entering
pi@raspberrypi:~/GarminDB $ /usr/bin/python3 garmin.py --weight --download --import --analyze --latest

**Comment by tcgoetz** [comment]
Some of the docs were out of data and I have updated them. You can download old data by adjusting the start dates in GarminConnectConfig.json and redownloading. Running garmin.py directing and choosing the options is always works. It just requires more knowledge of the program.
