### ISSUE TITLE
Parsing error

### ISSUE THREAD

**Issue by christian-ho** [tcgoetz/GarminDB#49]
With the latest 1.3.0 version I'm getting a parsing error when trying to do `make rebuild_dbs`

```
Failed to parse /home/christian/HealthData/FitFiles/Activities/3574713631.fit: 'int' object has no attribute '_name'
```

**Comment by tcgoetz** [comment]
Can you post the garmin.log for that run? It should have a call stack for that error.

**Comment by tcgoetz** [comment]
Is may also be useful if you can share 3574713631.fit with me.

**Comment by christian-ho** [comment]
Sry but I think the parsing hat nothing to do with the "rebuild db". The script did not delete all databases, after deleting them by hand it ran without stopping.

Nevertheless i attach the fit file, which didn't parse correctly.
[3574713631.zip](https://github.com/tcgoetz/GarminDB/files/4110448/3574713631.zip)

**Comment by EmptySoft** [comment]
Same to me, when i rebuild the database with `make_rebuild_dbs` i got the error message that the DB shema has been updated. (on develop tree)

**Comment by tcgoetz** [comment]
> Same to me, when i rebuild the database with make_rebuild_dbs i got the error message that the DB schema has been updated. (on develop tree)

@EmptySoft you get that message because the DB schema was updated on the develop branch
