### ISSUE TITLE
"There is no data to export for this date"

### ISSUE THREAD

**Issue by jhavens12** [tcgoetz/GarminDB#5]
When scraping the Garmin website i've seen this notice periodically pop up. Generally the screen is fully white and this popup comes up in the firefox window. It seems like this may happen when the page is not fully loaded and the script attempts to export data that is not yet available.

It does not always happen on the same date. For example I was updating the database and the script errored on 8/27/17. I removed the temp files and re-ran the script and it passed 8/27/17 without any issues.

The script then errors out completely and if you re-start - the program will begin again where the database has left off. This causes the script to re-download the zip files between the start date and the date where the error occured. It may be a good idea to have the script scan the temp folder where the zip files are downloaded first to see if there is anything left over from a previous scan? Otherwise you are forced to hope that the script completes before erroring so that the zip files may be moved to the incoming folder.

You can get around this by unzipping/moving the fit files to the incoming folder by hand, running the 

make import_monitoring

command and then removing the incoming fit files after they have been imported

**Comment by tcgoetz** [comment]
Closing as old.
