### ISSUE TITLE
Wrong sleepdata when no Data at Garmin Server

### ISSUE THREAD

**Issue by EmptySoft** [tcgoetz/GarminDB#50]
Hi.!

when I synchronize sleep data shortly after midnight, 7 hours is entered in GarminDB, although no sleep data is displayed via the web interface. If the sleep data are on the GaminServer synchroniced, the sleep totals still remain at 7 hours after rerun make.

**Comment by EmptySoft** [comment]
on the next day, the sleep data will be updated

**Comment by tcgoetz** [comment]
Try updating to commit 31067307f17d9e2b420371e1df631e5ee24b2aa5 on develop and see if it fixes this case.

**Comment by EmptySoft** [comment]
Thanks, it looks good
