### ISSUE TITLE
Missing activities

### ISSUE THREAD

**Issue by gabefortin** [tcgoetz/GarminDB#52]
Hi,

I'm impressed with what you've done. I have one issue so far though, I seem to be missing activities, particularly older ones but possibly others in between (not sure on this part though).

Here is what I think is the relevant part of my GarminConnectConfig.json file:
   "data" : {
        "weight_start_date"             : "25/12/2015",
        "sleep_start_date"              : "25/12/2015",
        "rhr_start_date"                : "25/12/2015",
        "monitoring_start_date"         : "25/12/2015",
        "download_days"                 : 1000,
        "download_latest_activities"    : 1000,
        "download_all_activities"       : 10000,
        "download_days_overlap"         : 3
    },

I first signed up for garmin connect on december 25th 2015 and have had activities since. But for some reason GarminDB hasn't downloaded any activities before 2016-09-27.

I have run 'make' several times since I first built the databases but it doesn't seem to be making a difference. A new activity from yesterday did download fine today though.

Any ideas?

Thanks!
Gabe

**Comment by tcgoetz** [comment]
Couple of questions:
- You can view these activities on connect.garmin.com?
- How many activities do you have total on connect.garmin.com? More than 1000?
- What command are running to download all of your data?

**Comment by gabefortin** [comment]
Hi,

Yes, I can view them on connect.garmin.com <http://connect.garmin.com/>
Yes I have more than 1000 activities on there.
I have just been running ‘make’ now after having run the setup and  creat_dbs earlier on.

Thanks
Gabe

**Comment by gabefortin** [comment]
I’m just running garmin.py right now without the —latest flag and it looks like it might be downloading some more (probably should have thought of that before!). Will see how it goes.

**Comment by gabefortin** [comment]
Yep, put that one down to operator error. I must have done something wrong when I first built the dbs and missed those. Ran and update without the --latest tag and all looks good now.

**Comment by tcgoetz** [comment]
You can also run `garmin.py --download --activities` (no --latest option) to download all activities (up to the limit set in the config).
