### ISSUE TITLE
Update to 1.4.0

### ISSUE THREAD

**Issue by christian-ho** [tcgoetz/GarminDB#54]
In your update instructions you mention an `download_create_dbs.sh` script. I can't find it in the git repo, is it only available in the mac-package?

**Comment by tcgoetz** [comment]
Instructions updated.

**Comment by christian-ho** [comment]
I suspect that `garmin_summary.db` and `summary.db` will not be deleted with `garmin.py --delete_db --all`. I had to delete them manually to make `make rebuild_dbs` run without error.

Could you check this please.

**Comment by tcgoetz** [comment]
commited to develop branch, will merge to master with next minor version release

**Comment by christian-ho** [comment]
`make rebuild_dbs` now works as expected.
