### ISSUE TITLE
"copy_create" and "download_create" scripts fail

### ISSUE THREAD

**Issue by ludwa6** [tcgoetz/GarminDB#59]
Following the Readme_MacOS.txt file to run the software in this repo, i get as far as trying both methods (2.a&b) to create the database, i.e.: 

> 2. Create your databases if you have not used the program previously by doing one of:
>     a. Run download_create_dbs.sh to create databases by downloading from the Garmin Connect website.
>     b. Run copy_create_dbs.sh to create databases from a USB connected Garmin device.

... And *both* methods fail with this same error message:
`line 6: ./garmin: No such file or directory`

This is strange, because i can see the file "garmin" (Unix executable) in this directory... But it seems the script cannot find it.  I have satisfied the necessary preconditions for both these scripts to run, i.e. 

- my Garmin sports watch is connected via USB; it shows up on as a volume in the Finder; and
- i have created a GarminConnectConfig.json file based on the example, with my own login credentials inserted as indicated.

Am running macOS HighSierra 10.13.6 ... and would *love* to get this software running, so i can make better use of all that valuable data i've been uploading to Garmin Connect!

**Comment by tcgoetz** [comment]
Are you using the binary release or checking out the repo?

**Comment by ludwa6** [comment]
Binary release.  / w

**Comment by tcgoetz** [comment]
How do you run `download_create_dbs.sh`? You should run it from a terminal session in the directory where you find download_create_dbs.sh. The file garmin should be in the same directory.

**Comment by tcgoetz** [comment]
If the above is not the issue, then please run `ls -la` in a the directory where the scripts live an attach the output.

My next through is that `garmin` does not have the executable bit set.

**Comment by ludwa6** [comment]
As requested, @tcgoetz , here's the output:

```
Last login: Tue Apr 14 08:57:57 on ttys000
MacBook-Pro:~ walterludwick$ cd /Applications
MacBook-Pro:Applications walterludwick$ cd ./GarminDb_Darwin_1.6.0
MacBook-Pro:GarminDb_Darwin_1.6.0 walterludwick$ ls
GarminConnectConfig.json		download_create_dbs.sh
GarminConnectConfig.json.example	download_update_dbs.sh
Readme_MacOS.txt			fitbit
bugreport.sh				garmin
checkup					graphs
copy_create_dbs.sh			mshealth
copy_update_dbs.sh
MacBook-Pro:GarminDb_Darwin_1.6.0 walterludwick$ ls -la
total 334456
drwx------@  16 walterludwick  admin       512 Apr 12 17:50 .
drwxrwxr-x+ 101 root           admin      3232 Apr 13 15:56 ..
-rw-r--r--@   1 walterludwick  admin      6148 Apr 12 17:50 .DS_Store
-rw-r--r--@   1 walterludwick  admin      1097 Apr 12 17:38 GarminConnectConfig.json
-rw-r--r--@   1 walterludwick  admin      1096 Feb  8 15:24 GarminConnectConfig.json.example
-rw-r--r--@   1 walterludwick  admin      1140 Dec 13 08:11 Readme_MacOS.txt
-rwxr-xr-x@   1 walterludwick  admin       872 Jan 23 07:32 bugreport.sh
-rwxr-xr-x@   1 walterludwick  admin  34127062 Mar  7 11:17 checkup
-rwxr-xr-x@   1 walterludwick  admin       242 Dec 10 06:19 copy_create_dbs.sh
-rwxr-xr-x@   1 walterludwick  admin       262 Dec 10 06:19 copy_update_dbs.sh
-rwxr-xr-x@   1 walterludwick  admin       255 Dec 10 06:19 download_create_dbs.sh
-rwxr-xr-x@   1 walterludwick  admin       274 Dec 10 06:19 download_update_dbs.sh
-rwxr-xr-x@   1 walterludwick  admin  34110639 Mar  7 11:18 fitbit
-rwxr-xr-x@   1 walterludwick  admin  34708523 Mar  7 11:16 garmin
-rwxr-xr-x@   1 walterludwick  admin  34135989 Mar  7 11:16 graphs
-rwxr-xr-x@   1 walterludwick  admin  34113796 Mar  7 11:18 mshealth
MacBook-Pro:GarminDb_Darwin_1.6.0 walterludwick$ 

```

**Comment by tcgoetz** [comment]
`garmin1 is executable and in the same directory as the script. So that is correct. I'm a little surprised that you put in in the Apps directory since it isn't an app. That may or may not matter.

> How do you run `download_create_dbs.sh`? You should run it from a terminal session in the directory where you find download_create_dbs.sh. The file garmin should be in the same directory.

How about this question?

**Comment by ludwa6** [comment]
Just as you say, @tcgoetz : i run download_create.db.sh in a terminal session -all in the same directory (which is located in the Apps directory, because that's where i keep all executable files.  Data generated by those docs, i generally point to Documents directory, once it begins to flow... But i'll often keep some test data files in the Applications directory, it is no problem).   /w

**Comment by tcgoetz** [comment]
I replicated your situation and it worked for me:

> orion-dock:GarminDb_Darwin_1.6.0 tgoetz$ ./download_update_dbs.sh
> Updating existing DBs by downloading from Garmin Connect
> ___Downloading Latest Data___
> Geting activities: '/Users/tgoetz/HealthData/FitFiles/Activities' (10)
> ...

**Comment by ludwa6** [comment]
Problem solved, @tcgoetz .  The problem was on my end, nothing to do with your code; once i cleaned up the problem, the `download_create_dbs.sh` script ran like a champ.  

The `copy_create_dbs.sh` script choked on what looks like a problem with what's stored on my watch, i.e.- `FileNotFoundError: [Errno 2] No such file or directory: '/Volumes/GARMIN/garmin/sleep'` -but that's my problem, not yours... So i'm gonna close this issue, with apologies for my blunder -and thanks for your patience, TC.  It is a great thing you have done, this!

**Comment by tcgoetz** [comment]
If /Volumes/GARMIN/garmin/sleep is not the proper path for your watch, you may need to change the config here: https://github.com/tcgoetz/GarminDB/blob/9337bb8dbdeb997a0d2afe3491382c5ff507821f/GarminConnectConfig.json.example#L17

**Comment by ludwa6** [comment]
Thanks, @tcgoetz -but i don't quite understand.  If i look into that volume called 'GARMIN' that appears when i plug my watch (a Forerunner 230) into USB port of my Mac, i see (besides 2 files) just one folder called 'Garmin', which contains some 17 subfolders, but none of them is called 'sleep'.  Am i missing something, or is that not a feature of this particular watch, i wonder?
