### ISSUE TITLE
garmin_activities.db empty

### ISSUE THREAD

**Issue by jhavens12** [tcgoetz/GarminDB#6]
I'm not sure if this is yet supported or not as it doesn't specify in the readme file, but the garmin_activities.db is created but nothing gets imported into it. I can see the tables and the columns, but no actual data.

Just curious if this should be populated with data or if it is part of a future plan.

Thanks

**Comment by tcgoetz** [comment]
This is work in progress. Right now if you manually download an activities file (go to an activity's page and click 'Export Original' under the gear drop down) and put the fit file into HealthData/FitFiles/Activities, then run `make import_activities` it will attempt to parse the file and put a summary record for the activity in "activities" table.

**Comment by tcgoetz** [comment]
See https://github.com/tcgoetz/GarminDB/wiki for future plans.

**Comment by jhavens12** [comment]
Awesome thanks!

**Comment by jhavens12** [comment]
Ill be watching for updates to this, currently im relying on Strava to hold all of my information. If I could have a local copy of it all that would be great

**Comment by jhavens12** [comment]
Have you seen this?

https://github.com/kjkjava/garmin-connect-export

**Comment by tcgoetz** [comment]
Try it. It hasn't been updated in 2 years. I think you'll find that the Garmin Connect website has changed and it not longer works. The scraper is the smallest part of GarminDB and the most brittle part. It needs to be updated whenever Garmin chnages the website.

**Comment by jhavens12** [comment]
I was able to get it to work using the command:

`python gcexport.py -d activities -c all -f original -u -d /Users/Havens/HealthData/FitFiles/Activities --username USER--password PASSWORD `

It looks like the functionality to get the GPX or TCX files out of the website is broken, but I was able to use it to extract the .fit files for the activities as well as create a CSV file that looks similar to your garmin_activity.db database tables

```
Garmin Connect activity: [1781622537] Treadmill - Morning Run
	Tue, Jan 10, 2017 9:57 AM, 00:48:57, 3.91 Miles
	Downloading file... Unzipping and removing original files... Done.
Garmin Connect activity: [1781623943] Treadmill - Morning Run
	Sat, Jan 7, 2017 1:38 PM, 01:00:03, 5.48 Miles
	Downloading file... Unzipping and removing original files... Done.
Garmin Connect activity: [1781625002] Treadmill - Morning Run
	Thu, Jan 5, 2017 9:59 AM, 00:44:17, 3.46 Miles
	Downloading file... Unzipping and removing original files... Done.
Garmin Connect activity: [1781626062] Treadmill - Morning Run
	Mon, Jan 2, 2017 1:37 PM, 00:57:24, 5.32 Miles
	Downloading file... Unzipping and removing original files... Done.
Done!
```

Might be helpful to you, might not be - just thought I'd mention it

**Comment by tcgoetz** [comment]
I'm surprised that still works after the GC rewrite, but since it does, I'm goign to look at pulling it in as a submodule and using it to download activity files.

My goal is do a deeper parse of the activity files. Not just what it is pulling out so far. That requires expanding the FIT file parser to handle new message types. I'm particularly interested in the data in sensor messages and similar.

**Comment by jhavens12** [comment]
Good to know! I actually opened an issue on that repo and someone redirected me to a more updated version:

https://github.com/moderation/garmin-connect-export

I haven't tried this one yet but this one looks like its been more recently maintained
