### ISSUE TITLE
I downloaded the zip, extracted it and ran make setup - this came back with an error can't find  DBParams in utilities, when I checked utilities folder it is empty.. I see you did a merge 16 days ago...

### ISSUE THREAD

**Issue by Dave-DigiMim** [tcgoetz/GarminDB#60]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Logs**
Please include a copy of screen logging and garmin.log.

**Please run bugreport.sh and attach bugreport.zip.**

**Additional context**

**Comment by tcgoetz** [comment]
Don't use the source archive. That;s something GitHub is doing to record whats ina release. It doesn't handle submodules.

You can use the binary release if your on MacOS. Otherwise you need to clone the repo and run the setup.

**Comment by tcgoetz** [comment]
Is your issue resolved?
