### ISSUE TITLE
branch develop missing get_string for Attributes

### ISSUE THREAD

**Issue by benbowen** [tcgoetz/GarminDB#63]
Looks like you've changed a ton since I last used this about 2 years ago!  I still haven't mentally  unpacked everything you did, but I'm seeing this error.  

```python
Traceback (most recent call last):
  File "garmin.py", line 342, in <module>
    main(sys.argv[1:])
  File "garmin.py", line 326, in main
    import_data(args.trace, args.latest, args.stats)
  File "garmin.py", line 178, in import_data
    measurement_system = GarminDB.Attributes.measurements_type(garmindb)
  File "/Users/bpb/repos/garmin_activity/GarminDB/GarminDB/garmin_db.py", line 46, in measurements_type
    return Fit.field_enums.DisplayMeasure.from_string(cls.get_string(db, 'measurement_system', default))
AttributeError: type object 'Attributes' has no attribute 'get_string'
```

I'm on develop branch. Environment is Python3 with your packages specified.

**Comment by tcgoetz** [comment]
I'm guessing your utilities submodule is not updated correctly.

get_string comes from: https://github.com/tcgoetz/utilities/blob/e0e980d349d66f8290d654a309b2aadd46200b76/key_value.py#L68 and your utilities/key_value.py should look like that.

You can run `make update` to get the submodules updated correctly.

**Comment by benbowen** [comment]
@tcgoetz Thanks! Sorry for nonissue and the long silence.  No programming for me the past month or so. I forgot about submodules thing.
