### ISSUE TITLE
rhr and inactive_hr in _graph_hr has different time vectors, causing a messed up plot

### ISSUE THREAD

**Issue by Grimler91** [tcgoetz/GarminDB#67]
**Describe the bug**

`graphs.py --hr --period weeks` gives, for me, a plot where the two y-data sets have different x-vectors, causing the plot to be more or less unreadable.

`graphs.py --hr --period days` and `graphs.py --hr --period months` works as intended, as does all other plots (weight, steps and so on).

Here's the graph:
![heart_rate_plot](https://user-images.githubusercontent.com/18900601/86517409-054b9f00-be29-11ea-896f-ecea4f0a563c.png)

If I remove the `self.__remove_discontinuities()` function call, i.e. apply this patch:

```diff
diff --git a/graphs.py b/graphs.py
index db1441d..92b9ec9 100755
--- a/graphs.py
+++ b/graphs.py
@@ -172,7 +174,7 @@ class Graph(object):
 
     def _graph_hr(self, time, data, period):
         rhr = [entry.rhr_avg for entry in data]
-        inactive_hr = self.__remove_discontinuities([entry.inactive_hr_avg for entry in data])
+        inactive_hr = [entry.inactive_hr_avg for entry in data]
         self.__graph_multiple(time, [rhr, inactive_hr], 'Heart Rate', period, ['RHR', 'Inactive hr'], [(30, 100), (30, 100)], self.save)
 
     def _graph_itime(self, time, data, period):

```

I get a graph that looks good for all time periods.

Running `self.__remove_discontinuities()` on rhr as well as inactive_hr also looks good, so I guess `__remove_discontinuities` should be run on both data sets (or neither)?

**To Reproduce**

`graphs.py --hr --period weeks`

**Expected behavior**

I expect to get a plot where the data sets are plotted against the same time period.

**Logs**

No interesting log output in this case.

**Additional context**

I am using GarminDB from the develop branch.

**Comment by tcgoetz** [comment]
__remove_discontinuities is needed for any data set that does not have data points for all time samples. The answer should be both.
