### ISSUE TITLE
AttributeError: type object 'Attributes' has no attribute 'get_string'

### ISSUE THREAD

**Issue by umaar** [tcgoetz/GarminDB#69]
Hey thanks for this project! Had just done a `git pull`, and now when I run the usual `make`, I see errors:

```bash
Downloading latest rhr data from: 2020-06-07
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 37/37 [00:46<00:00,  1.24s/days]
___Importing Latest Data___
Processing profile data
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 58.49files/s]
Processing [<FileType.settings: 2>] FIT data from /me/HealthData/FitFiles
Traceback (most recent call last):
  File "garmin.py", line 340, in <module>
    main(sys.argv[1:])
  File "garmin.py", line 324, in main
    import_data(args.trace, args.latest, args.stats)
  File "garmin.py", line 176, in import_data
    measurement_system = GarminDB.Attributes.measurements_type(garmindb)
  File "/me/GarminDB/GarminDB/garmin_db.py", line 46, in measurements_type
    return Fit.field_enums.DisplayMeasure.from_string(cls.get_string(db, 'measurement_system', default))
AttributeError: type object 'Attributes' has no attribute 'get_string'
      433.94 real         2.65 user         0.47 sys
make: *** [update_garmin] Error 1
```

Any ideas?

**Comment by umaar** [comment]
Saw your comment elsewhere to run `make update` thanks that fixed it

**Comment by Preliator-code** [comment]
Hey, did you find a solution? I have the same problem.

**Comment by tcgoetz** [comment]
Your working from the source tree? If so, then run `make update` at the top of the tree. You might considering using the release via `pip install garmindb` instead.

**Comment by Preliator-code** [comment]
I actually used "pip install garmindb" before. Here is how I did it:

- run "pip install garmindb"
- go to "C: \ Users \ Kevin \ AppData \ Local \ Programs \ Python \ Python37 \ Lib \ site-packages \ garmindb \ garmindb" and edit "GarminConnectConfig.json" to put my email and my password
- Run "garmindb_cli.py --all --download --import --analyze"
- There he says "No such file or directory: 'C: \\ Users \\ Kevin \\. GarminDb \\ GarminConnectConfig.json'
Missing config: copy GarminConnectConfig.json.example from c: \ users \ kevin \ appdata \ local \ programs \ python \ python37 \ lib \ site-packages \ garmindb to C: \ Users \ Kevin \ .GarminDb \ GarminConnectConfig.json and edit it to add your Garmin Connect username and password. "
- So, I copy paste "GarminConnectConfig.json" in "C: \ Users \ Kevin \ .GarminDb"
- Relaunch "garmindb_cli.py --all --download --import --analyze"
- Final error: "AttributeError: 'sessionmaker' object has no attribute 'begin'"


![2021-07-01_224244](https://user-images.githubusercontent.com/46316410/124187269-df99ba00-dabd-11eb-9cc8-b272261e9dd0.jpg)

**Comment by tcgoetz** [comment]
You need to update to a newer version of SQLAlchemy. See https://github.com/tcgoetz/GarminDB/issues/124
