### ISSUE TITLE
make import_monitoring errors when run

### ISSUE THREAD

**Issue by jhavens12** [tcgoetz/GarminDB#7]
I set up a fresh version of this on my machine to test and this is what I found:

```
GarminDB Havens$ make GC_DATE=06/07/2017 GC_DAYS=5 GC_USER=USER GC_PASSWORD=PW scrape_monitoring
mkdir -p /Users/Havens/HealthData/FitFiles/Incoming
python scrape_garmin.py -d 06/07/2017 -n 5 -u jhavens12@gmail.com -p NJKLIOJN0l*  -m "/Users/Havens/HealthData/FitFiles/Incoming"
No handlers could be found for logger "scrape_garmin.py"

GarminDB Havens$ make import_monitoring
mkdir -p /Users/Havens/HealthData/DBs
ls: /Users/Havens/HealthData/FitFiles/*Monitoring*/: No such file or directory
for dir in ; do \
		python import_garmin_fit.py -e --input_dir "/Users/Havens/HealthData/FitFiles/2018_Monitoring" --sqlite /Users/Havens/HealthData/DBs; \
	done
```
The first command now runs without issue, but when running the make import_monitoring function, the  program searches the monitoring folder but all of the fit files are actually placed in the "incoming" folder instead of the 2017_Monitoring or 2018_Monitoring folders

**Comment by tcgoetz** [comment]
'make import_monitoring'

is used to process the files that are in your ~HealthData/FitFiles/2018_Monitoring. this is used for things like rebuilding your DB.

To process newly scraped file:

    `make import_new_monitoring`

**Comment by jhavens12** [comment]
Ah thank you!
