### ISSUE TITLE
Help with Installation

### ISSUE THREAD

**Issue by jnannie** [tcgoetz/GarminDB#70]
I am super new to using terminal and what not. How on earth do I do step 3?! "3. Copy GarminConnectConfig.json.example to GarminConnectConfig.json, edit it, and add your Garmin Connect username and password."

Sorry for the super simple question. I searched everywhere for an answer before stopping here.

Thanks.

**Comment by tcgoetz** [comment]
That step doesn't need to be done in a terminal. Are you on MacOS or Windows or ...? On MacOS you can select GarminConnectConfig.json.example in Finder, copy, then paste. You will get a new file called GarminConnectConfig.json.example.copy or similar. Rename that file to GarminConnectConfig.json. Then right click on GarminConnectConfig.json and choose "open with" and choose an editor. Make you changes in the editor.

**Comment by jnannie** [comment]
Thank you,

After doing that, and running "copy_create_dbs.sh"

___Copying Data___
Traceback (most recent call last):
  File "garmin.py", line 341, in <module>
  File "garmin.py", line 319, in main
  File "garmin.py", line 82, in copy_data
  File "copy_garmin.py", line 29, in __init__
RuntimeError: Device mount directory /Volumes/GARMIN not found
[68297] Failed to execute script garmin

**Comment by tcgoetz** [comment]
You are running the script for copying data directly from a plugged in watch. Is that what you intend?

**Comment by jnannie** [comment]
Yes, as Garmin Connect and all their online services are down and will be for some time it seems.

**Comment by tcgoetz** [comment]
You can use GarminDB without accessing the Garmin websites. That is what `copy_create_dbs.sh` is for.

**Comment by jnannie** [comment]
Yes, when I use that command I get the area I previously posted.

**Comment by tcgoetz** [comment]
Where does your watch get mounted when you connect it to your computer? You need to change
"copy": { "mount_dir" : "/Volumes/GARMIN" },
in GarminConnectConfig.json Replace "/Volumes/GARMIN" with whereever your watch is mounted when you plug it into the computer.

**Comment by jnannie** [comment]
> Where does your watch get mounted when you connect it to your computer?

I have to use Android File Transfer to get the watch to show up, but it only shows up in the app. Any way to get the watch to show up as if it were a USB?

**Comment by jnannie** [comment]
It seems, for now, there's no way for Fenix 6X to show up where a USB usually would on mac due to recent changes by Garmin in the USB arena? It seems like once that is available and/or once Garmin connect is back online everything should work! Thanks for your help thus far!

**Comment by jnannie** [comment]
Successfully created a database, now how do I create graphs?

**Comment by tcgoetz** [comment]
`./graphs --all`
