### ISSUE TITLE
Garmin Servers down, import local?

### ISSUE THREAD

**Issue by EmptySoft** [tcgoetz/GarminDB#71]
Is it possibile to import the fit files directly from the watch to the DB?

`garmin.py --copy`

copies the settings to the HealthData/FitFiles. But what have i to do next?

**Comment by tcgoetz** [comment]
This make target does that:
`copy_garmin_latest:
	$(TIME) $(PYTHON) garmin.py --all --copy --import --analyze --latest`

You can use it by running `make copy_garmin_latest` or you can run it directly with `garmin.py --all --copy --import --analyze --latest`.

**Comment by tcgoetz** [comment]
You may need to change 
`"copy": {
        "mount_dir"                     : "/Volumes/GARMIN"
    },`
in GarminConnectConfig.json if your watch is mounted at "/Volumes/GARMIN" when you plug it in.

**Comment by EmptySoft** [comment]
Hi Tom.!

Thank you so much for your help. when i set mount_dir to 
`/srv/www/htdocs/nextcloud/data/harald/files/GARMIN`
it looks for
`/srv/www/htdocs/nextcloud/data/harald/files/garmin/garmin/settings`
(2 times garmin) OK, i change to
`/srv/www/htdocs/nextcloud/data/harald/files`
Thats OK. But now my Problem, on the Watch (Garmin Fexnix 3 hr) all Files are uppercase, your code looking for lowercase. Is my watch different? My system running Linux

**Comment by tcgoetz** [comment]
Your watch is mounted at `/srv/www/htdocs/nextcloud/data/harald/files/GARMIN`? That looks like its in the tree of a webserver. What OS and setup is this?

**Comment by EmptySoft** [comment]
This Dir is an Sync from my Laptop (running Linux) via Nextcloud to my Server, also running on Linux. But the Files on my Fenix 3 HR are in Uppercase. At this time i wrote a small script to transform the Files from uppercase to lowercase

**Comment by Grimler91** [comment]
@EmptySoft did you have to make some configuring to mount the watch? 

I have so far been unable to access my forerunner 945 on archlinux and have been tinkering with blacklisting the garmin_gps kernel module and adding udev rules as suggested on [this page](https://www.gpsbabel.org/os/Linux_Hotplug.html), but so far without success. 

With linux distro are you using?

**Comment by EmptySoft** [comment]
I am running SuSE Linix (15.2). There are no configurations at the watch or the OS, only connect the Watch (Garmin Fenix 3 HR), choose use USB at the watch and mount it via connected devices on the KDE

**Comment by tcgoetz** [comment]
Closing as old.
