### ISSUE TITLE
Generating graphs with Matplotlib 3.3

### ISSUE THREAD

**Issue by christian-ho** [tcgoetz/GarminDB#72]
When running `make graphs` I'm getting the following messages and the script stops:

`In /home/christian/.local/lib/python3.6/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle:
The text.latex.preview rcparam was deprecated in Matplotlib 3.3 and will be removed two minor releases later.`

The same applies to:
`mathtext.fallback_to_cm`
`validate_bool_maybe_none`
`savefig.jpeg_quality`
`keymap.all_axes`
`animation.avconv_path`
`animation.avconv_args`

and

`Support for setting the 'mathtext.fallback_to_cm' rcParam is deprecated since 3.3 and will be removed two minor releases later; use 'mathtext.fallback : 'cm' instead.`

Edit:
Hm sry, i think that's more a configuration problem on my side?

**Comment by tcgoetz** [comment]
I get that message too. It should not be fatal.

What is the command and options that you are running?

**Comment by christian-ho** [comment]
I just run `make graphs`

Unfortunately I have the problem, that no graph files are generated, and there are no error messages beside those mentioned above.

Is there a problem, if you run it on a headless server? I read something, that in this case you have to use the `Agg` backend of matplotlib?
--> `matplotlib.use('Agg')`

**Comment by tcgoetz** [comment]
The graph's component of GarminDB is not setup to run headless. It generates a window as part of creating the graphs.

**Comment by christian-ho** [comment]
Okay, too bad ;-)

**Comment by tcgoetz** [comment]
That doesn't mean it couldn't run headless. It's just not setup for that. Do you want to submit a patch with that functionality?

**Comment by christian-ho** [comment]
Sry but I am a complete beginner in python and github, maybe later sometime.
