### ISSUE TITLE
Activity stop_time shows as "NULL"

### ISSUE THREAD

**Issue by skrasnow** [tcgoetz/GarminDB#73]
**Describe the bug**
Since 7/31/2020 the stop time for my walking activities shows as NULL (in the SQLite DB) and therefore (I suppose) the elapsed time showing up in the SQLite DB is highly incorrect.  I am running the latest version of the software (1.7).  I am wondering if this is caused by Garmin or is the error somewhere else.  Thank you. 

**To Reproduce**

**Expected behavior**

**Logs**
Please include a copy of screen logging and garmin.log.

**Please run bugreport.sh and attach bugreport.zip.**

**Additional context**

**Comment by tcgoetz** [comment]
I see the same thing. I will look into it.

**Comment by tcgoetz** [comment]
Please test something for me. Please go to one of your activities that is wrong in the DB and choose "export original" from the drop down menu from the cog icon. Does it work?

![Screen Shot 2020-08-02 at 8 21 26 PM](https://user-images.githubusercontent.com/15090876/89135787-ed396f00-d4fd-11ea-912f-c22fb3c85d1e.jpg)

**Comment by tcgoetz** [comment]
https://www.reddit.com/r/Garmin/comments/i1p3z1/garmin_connect_export_original/

**Comment by skrasnow** [comment]
Thank you, Tom.  I'm not sure I understand what you want, but attached is a
CSV of today's activity which is incorrect in the SQLite Db, but it has the
correct elapsed time on the Garmin site.

Stan  Krasnow
| わ | email: skrasnow@gmail.com | telephone: +1-914-282-1430 | skype:
stanleyk |

**Comment by tcgoetz** [comment]
I was asking if , on the Garmin Connect website, whether "Export Original" works for you fro the activities that are having issues. I does not for me. I get a 400 web error. Same as a lot of other people per the article sited above.

**Comment by skrasnow** [comment]
Thank you, Tom; yes, I got a "400 Bad request" as well.

Stan Krasnow
| わ | email: skrasnow@gmail.com | telephone: +1-914-282-1430 | skype:
stanleyk |

**Comment by tcgoetz** [comment]
It's working again. Runt hew following to download any activities files that were not previously downloaded:
`garmin.py --activities --download`

**Comment by skrasnow** [comment]
Thank you, Tom!  Agreed - the elapsed times are now in the DB correctly.

Stan Krasnow
| わ | email: skrasnow@gmail.com | telephone: +1-914-282-1430 | skype:
stanleyk |
