### ISSUE TITLE
On Activity Import: Failed to Parse [...] 'Centimeters' 

### ISSUE THREAD

**Issue by jbeimler** [tcgoetz/GarminDB#77]
**Describe the bug**
While importing activities recently I see the following:
Processing [<FileType.activity: 4>] FIT data from /Users/jbeimler/HealthData/FitFiles/Activities
`Failed to parse /Users/[...]/5513035670.fit: 'Centimeters'`

**To Reproduce**
1. Run `make` in the source folder
2. See errors above
3. Profit!

**Expected behavior**
I expect this to work and import, I want to take the time to dig in but I've not had time, so I am here for tips on where I can look to find this and help fix it.

**Logs**
`Processing [<FileType.activity: 4>] FIT data from /Users/jbeimler/HealthData/FitFiles/Activities
  0%|                                                                                              | 0/12 [00:00<?, ?files/s]Failed to parse /Users/jbeimler/HealthData/FitFiles/Activities/5496798698.fit: 'Centimeters'
Failed to parse /Users/jbeimler/HealthData/FitFiles/Activities/5497636338.fit: 'Centimeters'
 33%|████████████████████████████▋                                                         | 4/12 [00:03<00:07,  1.05files/s]Failed to parse /Users/jbeimler/HealthData/FitFiles/Activities/5522223503.fit: 'Centimeters'
Failed to parse /Users/jbeimler/HealthData/FitFiles/Activities/5497422238.fit: 'Centimeters'
Failed to parse /Users/jbeimler/HealthData/FitFiles/Activities/5502790404.fit: 'Centimeters'
Failed to parse /Users/jbeimler/HealthData/FitFiles/Activities/5497458178.fit: 'Centimeters'
 75%|████████████████████████████████████████████████████████████████▌                     | 9/12 [00:06<00:02,  1.19files/s]Failed to parse /Users/jbeimler/HealthData/FitFiles/Activities/5513035670.fit: 'Centimeters'
 92%|█████████████████████████████████████████████████████████████████████████████▉       | 11/12 [00:07<00:00,  1.27files/s]Failed to parse /Users/jbeimler/HealthData/FitFiles/Activities/5502809099.fit: 'Centimeters'
100%|█████████████████████████████████████████████████████████████████████████████████████| 12/12 [00:07<00:00,  1.55files/s]`

**Please run bugreport.sh and attach bugreport.zip.**

[garmin.log](https://github.com/tcgoetz/GarminDB/files/5212035/garmin.log)
[bugreport_1599875912.zip](https://github.com/tcgoetz/GarminDB/files/5212038/bugreport_1599875912.zip)

**Additional context**

Let me know where to start and I'll dig in, I've just not had enough time to trace this down yet.  Thanks for this project, helps me out a lot with maintaining my own analytics with little extra work.

**Comment by tcgoetz** [comment]
If you can share 5502809099.fit or another one of the files with the "failed to parse" message, I can fix the parsing.

**Comment by jbeimler** [comment]
Sorry, wasn't paying attention over here, I grabbed new data today, and I've attached a file that failed with the Centimeter issue.
[fitfile.zip](https://github.com/tcgoetz/GarminDB/files/5273205/fitfile.zip)

**Comment by tcgoetz** [comment]
This file works for me with the latest release. Please try it with the latest release.

**Comment by jbeimler** [comment]
Switched from master to the v 1.8.0 files and still get the same error on the same file. 

I also tried make rebuild_dbs to see if I had messed something up there and again had the same error. I'll clean everything out and try again overnight, and let you know if that fixed it.

Thanks so much for the help, appreciate it.

**Comment by jbeimler** [comment]
Removing the database, bumping the tag to the released version and re-running the script fixed things.

Thanks for putting up with me, hopefully at some point I can dig further in and try to help myself and others more.
