### ISSUE TITLE
Explanation for some GarminConfig Settings

### ISSUE THREAD

**Issue by nicolae-stroncea** [tcgoetz/GarminDB#78]
First, thanks for a fantastic project which gives me safety of mind of having my own data(especially in light of Garmin getting hacked) and being able to analyse it with my own tools!

I'm not clear on some of the configuration in the Settings and couldn't find explanations in the README or the file itself, so was hoping you'd be able to explain them.

The majority of the settings are very straightforward, below are the ones I'm not sure about:

```
        "download_days"                 : 31,
        "download_latest_activities"    : 20,
        "download_all_activities"       : 1000,
        "download_days_overlap"         : 3

```

**Comment by tcgoetz** [comment]
https://github.com/tcgoetz/GarminDB/wiki/Config
