### ISSUE TITLE
Question: What commands to run after pulling new commits from remote?

### ISSUE THREAD

**Issue by nicolae-stroncea** [tcgoetz/GarminDB#79]
Do we  need to run `make setup` every time that we pull in new commits when building from source?

I'm currently just running `make` even though some commits have piled on top, and am unsure if that runs with the new changes.

**Comment by tcgoetz** [comment]
Only if the new commits include changes to a requirements.txt. It's probably easier just to run it then to see if one of those files changed in any of the repos.
