### ISSUE TITLE
Problem with Release 1.8 - garmin.py

### ISSUE THREAD

**Issue by ParzivalWins** [tcgoetz/GarminDB#81]
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 10/10 [00:15<00:00,  1.54s/activities]
Traceback (most recent call last):
  File "garmin.py", line 340, in <module>
  File "garmin.py", line 321, in main
  File "garmin.py", line 125, in download_data
  File "garmin.py", line 71, in __get_date_and_days
TypeError: '<' not supported between instances of 'NoneType' and 'int'
[6473] Failed to execute script garmin

**Comment by fricour** [comment]
Hi,
Same issue here.
![image](https://user-images.githubusercontent.com/32942921/95674643-d07e7f00-0bb1-11eb-9378-9777d22e76a0.png)

**Comment by karlicoss** [comment]
Looks like it happened in [this](https://github.com/tcgoetz/GarminDB/commit/2de92b2a675c1586c2ab835c296b26a74f29d70e) commit. 

Changing this line 
https://github.com/tcgoetz/GarminDB/blob/265678bf9eae074ccc2fbd6d1555d204575e77f2/garmin_connect_config_manager.py#L73 to `days = (datetime.datetime.now().date() - date).days` fixes the issue, although not sure if it's the right thing to do.

**Comment by tcgoetz** [comment]
Added to develop branch.
