### ISSUE TITLE
Duplicate Items - Garmin Activities DB

### ISSUE THREAD

**Issue by skrasnow** [tcgoetz/GarminDB#83]
**Describe the bug**
For the last two days, the Garmin Activities DB has had duplicate records for the same walking workout. The attached .png image of the SQLiteStudio screen shows the duplicate records in the first four lines.  Notice that the activity id is the same except it is augmented by text in one of the records. The first and second lines are duplicative as are the third and fourth lines.  This just started to happen,  The data on the Garmin Connect website does not contain the duplicated records, as I read the site.  As a consequence of this duplication, the daily summary record has double the activity_distance is should have.

I tried to reload the database using the download_create_dbs.sh script and every record in the activities db was duplicated as described above.

**Below are links to the bug report and the screen shot.**
[bugreport_1604676261.zip](https://github.com/tcgoetz/GarminDB/files/5502008/bugreport_1604676261.zip)
![Activities DB Screenshot 11-06-2020](https://user-images.githubusercontent.com/60006115/98383803-f5cca480-201a-11eb-98d9-57b00fd0eece.png)

**Comment by skrasnow** [comment]
I am running version 1.8 under OSX.

**Comment by tcgoetz** [comment]
I'm seeing the same thing. Looking into it. Guessing the JSON now has "#_ACTIVITY" in it.

**Comment by tcgoetz** [comment]
Fixed on the develop branch. Please try that branch and confirm.

**Comment by skrasnow** [comment]
Tom - I can not figure out how to do what you're asking because I run from the binary re;ease of the code, a file simply named garmin.  If that file exists in the "develop branch",  I was unable to find it, and I'm not able to find out how to make one.  Standing by.  Thank you.  Stan

**Comment by tcgoetz** [comment]
https://github.com/tcgoetz/GarminDB/releases/tag/v1.8.1
