### ISSUE TITLE
setup error with 'make create_dbs'

### ISSUE THREAD

**Issue by sdimov2** [tcgoetz/GarminDB#84]
I am running this on windows 10, but I am using Ubuntu WSL and downloaded what I believe to be all the dependencies: sqlalchemy, dateutil, tqdm, make, and python of course. I am simply trying to run the command from the initial setup: 'make create_dbs', but It prompts me with the error message: 

File "/mnt/c/Users/sdimo/Git/Repositories/GarminDB/garmin_connect_config_manager.py", line 73, in stat_start_date
    days = (datetime.datetime.now() - date).days
TypeError: unsupported operand type(s) for -: 'datetime.datetime' and 'datetime.date'
Command exited with non-zero status 1
/usr/bin/time
make: *** [Makefile:131: garmin] Error 1

It appears to have a problem with the minus sign, I think using two different data types in line 73. I do not know if this is a result of another missing dependency or as a result of the OS I am using. 

I am not sure how to reproduce this problem since I think it is because of my OS or dependencies, but if necessary info, just have windows 10 and WSL and install all of the dependencies I mentioned above and go through the process of following the initial setup up to the instruction: make create_dbs

I haven't gone past this so I wouldn't know what to expect for anything.

**Comment by tcgoetz** [comment]
Fixed on the develop branch. Please try that branch and confirm.

**Comment by sdimov2** [comment]
It seems to have fixed the problem! I am now able to do make create_dbs and use make afterward.
