### ISSUE TITLE
dev fields not in DB even if  ignore_dev_fields is false

### ISSUE THREAD

**Issue by p3dr01978** [tcgoetz/GarminDB#88]
Hi,
I'm importing all my data from Garmin and I was expecting to find all the dev data in db, however all the dev data are ignored.

I see that in the fit processing the dev fields are present 

{'timestamp': datetime.datetime(2020, 11, 11, 0, 5, 35, tzinfo=datetime.timezone.utc), 'distance': 0.0, 'altitude': 239.20000000000005, 'unknown_87': 0.0, 'heart_rate': 62.0, 'cadence': 0.0, 'temperature': 30.0, 'fractional_cadence': 0.0, 'unknown_135': 2.0, 'unknown_136': 62.0, 'dev_AvgPulse': 61.0, 'dev_RMSSD': 58.502769470214844, 'dev_LnRMSSD': 228.0, 'dev_SDNN': 66.23906707763672, 'dev_SDSD': 43.35545349121094, 'dev_NN50': 81.0, 'dev_pNN50': 28.421052932739258, 'dev_NN20': 160.0, 'dev_pNN20': 56.140350341796875, 'dev_Long': 2.0, 'dev_Short': 1.0, 'dev_Ectopic-R': 0.0}

However they are not imported in the DB, is this a desiderata or is it a bug?

Thanks

**Comment by tcgoetz** [comment]
The FIT library can parse dev fields, but the dev fields will only be in the DB if they were coded in. The DB schema is fixed and the DB can't handle arbitrary data.

What app is the dev data you have in you message from? What does it represent? If I know what the data is, where it comes from, and what you can do with it, I can add it to the DB schema.

**Comment by p3dr01978** [comment]
They are data from HRV Analysis. (RMSSD,NN50,NN20)
In the while I've already added them to the schema and also the importer :)

Mirco

Il giorno lun 16 nov 2020 alle ore 15:55 Tom Goetz <notifications@github.com>
ha scritto:

**Comment by tcgoetz** [comment]
If this is data from an app that a lot of people will use, do you want to make a pulll request to merge it? If so, make the Pr against the develop branch.
