### ISSUE TITLE
Make Setup does not download Fit Module

### ISSUE THREAD

**Issue by jhavens12** [tcgoetz/GarminDB#9]
Running make setup on a new install gives the following error:

> GarminDB Havens$ make setup
> git submodule init
> Submodule 'Fit' (https://github.com/tcgoetz/Fit.git) registered for path 'Fit'
> Submodule 'garmin-connect-export' (https://github.com/tcgoetz/garmin-connect-export.git) registered for path 'garmin-connect-export'
> Submodule 'python-tcxparser' (https://github.com/tcgoetz/python-tcxparser.git) registered for path 'python-tcxparser'
> git submodule update
> Cloning into '/Users/Havens/Documents/GitHub/GarminDB/Fit'...
> Cloning into '/Users/Havens/Documents/GitHub/GarminDB/garmin-connect-export'...
> Cloning into '/Users/Havens/Documents/GitHub/GarminDB/python-tcxparser'...
> error: Server does not allow request for unadvertised object 5b58d4f5b7e59f859a69200fc51819ecc748d0ef
> Fetched in submodule path 'Fit', but it did not contain 5b58d4f5b7e59f859a69200fc51819ecc748d0ef. Direct fetching of that commit failed.
> make: *** [submodules_update] Error 1

**Comment by tcgoetz** [comment]
should be fixed now
